### ISSUE TITLE
Arms bug

### ISSUE THREAD

**Issue by rajkodev** [Kxnrl/Store#104]
Hello Kyle,

I already send you message on Telegram but I think that is better to share problem with others here.
There is a bug with hands, I used olders versions of shop but on latest development build i facing this kind of bug (see screenshots).

Also i compilled plugin with arms fix:

`//fix arms when client team
#if defined GM_MG **|| defined GM_RS**
#define TeamArms`

![20200104185225_1](https://user-images.githubusercontent.com/24896853/71967919-52491280-3204-11ea-8c56-df9d2a534b3c.jpg)
![20200104185343_1](https://user-images.githubusercontent.com/24896853/71967921-52e1a900-3204-11ea-8d0d-d47f6e4898d8.jpg)
![20200104185348_1](https://user-images.githubusercontent.com/24896853/71967922-52e1a900-3204-11ea-8803-342555245896.jpg)

**Comment by Kxnrl** [comment]
armsfix plugin was broken, moved to armsfix extension
