### ISSUE TITLE
unable to disable defaultskin module

### ISSUE THREAD

**Issue by oylsister** [Kxnrl/Store#105]
I moved skin_defaultskins plugin to the disabled folder. but somehow it's still working without the plugin, I tried changing the default model (which was SAS model according to your store_defaultskins.smx plugin) to the custom model that I have installed it. when I spawned again, I  saw the custom arms, but then the arm model changed to default one.

even I checked on the sm plugins list, there still don't have store_defaultskins plugin in the list.

**Comment by Kxnrl** [comment]
check your gamemode_server.txt
