### ISSUE TITLE
how disable skin level and desc in skin menu?

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#106]
![grafik](https://user-images.githubusercontent.com/13827296/72202311-1f9a5680-345e-11ea-89ad-79c5bde90fe5.png)

lvls fixed it's 0

**Comment by Caaine** [comment]
disable desc in skin menu how? :D

**Comment by Kxnrl** [comment]
that value in yoru database is equal with 'ITEM_NO_DESC'?
