### ISSUE TITLE
Some Questions - Issues

### ISSUE THREAD

**Issue by zo6zo6** [Kxnrl/Store#107]
I am trying to setup this plugin on the server and i am having a few questions - problems with it.

Question:
1st) is it possible to make the same player skins available for both teams?
2nd) how player skin lvls work and how can you buy a higher lvl skin?

Issues/Bugs
1st) When i equip wings on my player i can only see them in ct. if i switch to terrorists i cannot see the wings any more even if i have them equipped
2nd) I am trying to add subcategories to parent categories. i can import the parent on my database without issues but i can't import items inside the subcategories. i am quoting below my items.txt and the errors from insertitem.php

items.txt
[https://pastebin.com/MRMrishX](url)

insertitem.php
[https://pastebin.com/5XizrNyV](url)

i am also attaching a screenshot from parents in database
![parents](https://user-images.githubusercontent.com/18053332/72667111-f6ab3000-3a20-11ea-9c0e-493355b06d08.jpg)

i have also added you to steam, if you wish to accept my profile is the following
[https://steamcommunity.com/id/xtreme19zo6zo6/](url)

**Comment by Kxnrl** [comment]
A:
1. Of course
2. provide API only
 
Bug:
1. if u switch from CS_SwitchTeam, must be enable 
```sourcepawn
#define TeamArms
```
2. this is an example,
![image](https://user-images.githubusercontent.com/3905845/72667213-5b33b280-3a54-11ea-98f8-d7db345ab12d.png)

**Comment by zo6zo6** [comment]
i haven't understand a single thing, sorry for that but i know nothing about coding. i will try to explain better.

in zeph store if you wanted the skins to be available for both teams you could set team value to 4 and it was working. in this store "team" can only accept values of 2(t) or 3(ct). how can i make them available for both teams?
i still cant understand how case levels work.

now about wings. i switch team by pressing "M" when in the server and when i respawn in Terrorists i see no wings.

I have inserted parents successfully but the problem comes when i try to insert player skins. insertItem.php will not add the skins to the database at all

**Comment by Kxnrl** [comment]
u just compile plugins with enable 
```sourcepawn
#define Global_Skin
```
see store.sp  line 66



can u share the insertItem.php outputs?

**Comment by Kxnrl** [comment]
of just use store_jb.smx and rename to store.smx. this predefine using skin for both team

**Comment by zo6zo6** [comment]
i did. its the pastebin in my first post. i tried compiling the plugin for different reasons and it always failed.

**Comment by zo6zo6** [comment]
> of just use store_jb.smx and rename to store.smx. this predefine using skin for both team

i also need other things enabled. is there a list with all the features enabled in every one of the gamemodes?

**Comment by Kxnrl** [comment]
https://build.kxnrl.com/Store/Env.7z 
try this compile environment.

**Comment by zo6zo6** [comment]
> https://build.kxnrl.com/Store/Env.7z
> try this compile environment.

i'll try right now

**Comment by Kxnrl** [comment]
> > of just use store_jb.smx and rename to store.smx. this predefine using skin for both team
> 
> i also need other things enabled. is there a list with all the features enabled in every one of the gamemodes?

Line 147 - Line 187 is modules definition

**Comment by zo6zo6** [comment]
> > > of just use store_jb.smx and rename to store.smx. this predefine using skin for both team
> > 
> > 
> > i also need other things enabled. is there a list with all the features enabled in every one of the gamemodes?
> 
> Line 147 - Line 187 is modules definition

is there a version with everything included? all modules active?

**Comment by Kxnrl** [comment]
> > > > of just use store_jb.smx and rename to store.smx. this predefine using skin for both team
> > > 
> > > 
> > > i also need other things enabled. is there a list with all the features enabled in every one of the gamemodes?
> > 
> > 
> > Line 147 - Line 187 is modules definition
> 
> is there a version with everything included? all modules active?

yes, but without TP.

**Comment by zo6zo6** [comment]
> > > > > of just use store_jb.smx and rename to store.smx. this predefine using skin for both team
> > > > 
> > > > 
> > > > i also need other things enabled. is there a list with all the features enabled in every one of the gamemodes?
> > > 
> > > 
> > > Line 147 - Line 187 is modules definition
> > 
> > 
> > is there a version with everything included? all modules active?
> 
> yes, but without TP.

which one is it? 
not having tp is not an issue

**Comment by Kxnrl** [comment]
store_jb

**Comment by zo6zo6** [comment]
> store_jb.smx
> but u need to rename to store.smx

perfect, i'll try it.

now trying to compile the sp gave me this error: error 092: number of arguments does not match definition

and there is still the problem wtih insertitem.php not inserting skins in the database

**Comment by Kxnrl** [comment]
> > store_jb.smx
> > but u need to rename to store.smx
> 
> perfect, i'll try it.
> 
> now trying to compile the sp gave me this error: error 092: number of arguments does not match definition
> 
> and there is still the problem wtih insertitem.php not inserting skins in the database

Line?

**Comment by zo6zo6** [comment]
> > > store_jb.smx
> > > but u need to rename to store.smx
> > 
> > 
> > perfect, i'll try it.
> > now trying to compile the sp gave me this error: error 092: number of arguments does not match definition
> > and there is still the problem wtih insertitem.php not inserting skins in the database
> 
> Line?

// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(644) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(647) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(879) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2080) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2098) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2669) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2769) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2819) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2988) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(2997) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(3038) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(3066) : error 092: number of arguments does not match definition
// D:\Firefox_Downloads\STORE COMPILER\store_jb.sp(3852) : error 092: number of arguments does not match definition

**Comment by zo6zo6** [comment]
during my resting wings stopped appearing with every game mode of the plugin installed

**Comment by Kxnrl** [comment]
I tested on all servers. didn't find this problem.
can you share plugins list?

**Comment by zo6zo6** [comment]
i'll do a little more testing and report my findings

**Comment by Kxnrl** [comment]
okay
