### ISSUE TITLE
Questions :)

### ISSUE THREAD

**Issue by LubricantJam** [Kxnrl/Store#108]
Hey,

Apologies for not looking this up, couldn't find anything on it.

Is there a possibility to limit certain items for certain servers on the store? As I see you've converted the items.txt to MySQL but is that to make it MySQL dependent or is the .txt file still used?

I'd love it to be all MySQL but I don't see any fields where I can specify what servers load what. For example, I'd like my Arena servers not to have certain player models as they're a hindrance but would like them to be on Surf & Bunny Hop and have default CS:GO player models to load on just Arena.

Cheers.

**Comment by PandahChan** [comment]
EN:
To further explain this to you @Kxnrl what he's trying to say is this.
Currently the plugin takes all modules on compile time and decides what is used and what isn't used. Which can be okay for some people however can be tedious for others having to edit the *.sp file every single time to disable modules which was unneeded, potentially changing the way it compiles currently and allowing users to enable and disabling modules via ConVars

In regards to his comment on item's. He's trying to ask if there is a way to restrict certain items on certain servers. E.G: "Fun player models" on surf but not on serious competitive servers. Can this be limited within in items.txt or is this not a possible way of doing so.

CH:
当前，该插件在编译时获取所有模块，并确定使用和不使用的模块。 这对于某些人来说很好，但是对于其他人来说，每次都必须编辑* .sp文件以禁用不需要的模块可能很麻烦，这可能会更改当前的编译方法，并允许用户通过ConVars启用它并禁用模块。

关于他对该项目的评论。 他试图问是否有办法限制某些服务器上的某些项目。 例如：“自定义播放器模型”可以在非竞争服务器上使用，但不能在竞争服务器上使用。 可以将其限制为items.txt吗，或者这不是可行的方法。

抱歉，如果有翻译问题，我的中文不是很好。

**Comment by LubricantJam** [comment]
Anything?

**Comment by Kxnrl** [comment]
convar to control module loading -> performance issues.

if u wana use custom player model for classic game mode only, just remove player model files from competitive server. 

store will check the files exists on load, if file does not exists, just skip that item

**Comment by Kxnrl** [comment]
I use 1 sql table to control all game modes.
ZE, MG, TTT, JB, retakes, Surf, BHOP, KZ, HG and more.

**Comment by LubricantJam** [comment]
Oh, so if the files don't exist it won't load? Brilliant, that's exactly what I want :) Thank you and sorry for the bump!

**Comment by Kxnrl** [comment]
> Oh, so if the files don't exist it won't load? Brilliant, that's exactly what I want :) Thank you and sorry for the bump!

sure, such as I added a playerskin named Lilia in database.
I installed model mdl files to MG server. 
you can see that  in !store menu in MG server.
But you can not see that in other servers.

but except namecolor, msgcolor, nametag

**Comment by LubricantJam** [comment]
So after I have converted, will I need items.txt or can this be deleted?

**Comment by Kxnrl** [comment]
yes, u should delete that.
