### ISSUE TITLE
loaditem.php Issues

### ISSUE THREAD

**Issue by LubricantJam** [Kxnrl/Store#114]
Finally got to the last hurdle of importing, we've just got this left. 

Any ideas on as to why this would be happening? Also, seems a file is missing.

```
Warning: fclose() expects parameter 1 to be resource, boolean given in loaditem.php on line 79
8802. 'models/player/holiday/facemasks/facemask_pumpkin.mdl' has not found in child
Warning: fopen(errorlog.php): failed to open stream: Permission denied in loaditem.php on line 75
```
This is happening for every item.

**Comment by Kxnrl** [comment]
can u share items.txt?
did u run script with php-cli?

**Comment by LubricantJam** [comment]
Sure, here it is.
https://lubricantjam.com/uploads/2020/02/06/items.txt

No, I ran it by putting it on my webserver and browsing the URL.

**Comment by LubricantJam** [comment]
Formatting is a tad weird but is fine on Visual Studio Code.

**Comment by LubricantJam** [comment]
It's deleting like 90% of my items for some reason.

errorlog.php
https://lubricantjam.com/uploads/2020/02/07/2020-02-07_10-41-05.txt
debug on page
https://lubricantjam.com/uploads/2020/02/07/2020-02-07_10-41-29.txt

**Comment by LubricantJam** [comment]
It seems you're doing a loop for all store_items to check if the item has a name but on zeph store, no items have a name? So it's just deleting all my purchased items.

**Comment by Kxnrl** [comment]
u should import parent before importing itmes

**Comment by LubricantJam** [comment]
I have done so, I follow the exact method you post on the README. insertParent, insertItem then loaditem.
