### ISSUE TITLE
Crash on client join server

### ISSUE THREAD

**Issue by Kroytz** [Kxnrl/Store#119]
`Host_Error: Bad string:`

Using sm 1.10.6461
mm 1.10.7-dev

`[SM] Listing 65 plugins:
  01 "Admin File Reader" (1.10.0.6461) by AlliedModders LLC
  02 "Admin Help" (1.10.0.6461) by AlliedModders LLC
  03 "Admin Menu" (1.10.0.6461) by AlliedModders LLC
  04 "[CS:GO] Enforce Alltalk " (1.2) by IT-KiLLER
  05 "Anti-Flood" (1.10.0.6461) by AlliedModders LLC
  06 "Basic Ban Commands" (1.10.0.6461) by AlliedModders LLC
  07 "Basic Chat" (1.10.0.6461) by AlliedModders LLC
  08 "Basic Comm Control" (1.10.0.6461) by AlliedModders LLC
  09 "Basic Commands" (1.10.0.6461) by AlliedModders LLC
  10 "Basic Info Triggers" (1.10.0.6461) by AlliedModders LLC
  11 "Basic Votes" (1.10.0.6461) by AlliedModders LLC
  12 "Client Preferences" (1.10.0.6461) by AlliedModders LLC
  13 <Failed> "Chat Processor - Simple Chat Processor Wrapper" (1.0.0) by Keith
Warren (Shaders Allen)
  14 <Failed> "[Source 2013] Custom Chat Colors" (3.1.0 CP) by Dr. McKay, Fixed
up by Keith Warren (Drixevel)
  15 "Fun Commands" (1.10.0.6461) by AlliedModders LLC
  16 "Fun Votes" (1.10.0.6461) by AlliedModders LLC
  17 "Store - Default player skins" (2.3.598) by Kyle
  18 "Store - Give credits command" (2.3.598) by Kyle
  19 "Store - Pets" (2.3.598) by Kyle
  20 "MyJailbreak - Arms Race" (Beta 14.0-148fccd) by shanapu
  21 "MyJailbreak - Catch & Freeze" (Beta 14.0-148fccd) by shanapu
  22 "MyJailbreak - CowBoy" (Beta 14.0-148fccd) by shanapu
  23 "MyJailbreak - DealDamage" (Beta 14.0-148fccd) by shanapu
  24 "MyJailbreak - Drunk" (Beta 14.0-148fccd) by shanapu
  25 "MyJailbreak - DuckHunt" (Beta 14.0-148fccd) by shanapu
  26 "MyJailbreak - War FFA" (Beta 14.0-148fccd) by shanapu
  27 "MyJailbreak - Freeday" (Beta 14.0-148fccd) by shanapu
  28 "MyJailbreak - Ghosts War" (Beta 14.0-148fccd) by shanapu
  29 "MyJailbreak - HE Battle" (Beta 14.0-148fccd) by shanapu
  30 "MyJailbreak - HideInTheDark" (Beta 14.0-148fccd) by shanapu
  31 "MyJailbreak - Player HUD" (Beta 14.0-148fccd) by shanapu
  32 "MyJailbreak - Icons" (Beta 14.0-148fccd) by shanapu
  33 "MyJailbreak - KnifeFight" (Beta 14.0-148fccd) by shanapu
  34 "MyJailbreak - Last Guard Rule" (Beta 14.0-148fccd) by shanapu
  35 "MyJailbreak - Menus" (Beta 14.0-148fccd) by shanapu
  36 "MyJailbreak - Core" (Beta 14.0-148fccd) by shanapu
  37 "MyJailbreak - NoScope" (Beta 14.0-148fccd) by shanapu
  38 "MyJailbreak - OneInTheChamber" (Beta 14.0-148fccd) by Hexah | shanapu
  39 "MyJailbreak - PlayerTags" (Beta 14.0-148fccd) by shanapu
  40 "MyJailbreak - Ratio" (Beta 14.0-148fccd) by shanapu, Addicted
  41 "MyJailbreak - Request" (Beta 14.0-148fccd) by shanapu
  42 "MyJailbreak - Suicide Bomber" (Beta 14.0-148fccd) by shanapu
  43 "MyJailbreak - Teleport War" (Beta 14.0-148fccd) by shanapu
  44 "MyJailbreak - Torch Relay" (Beta 14.0-148fccd) by shanapu
  45 "MyJailbreak - War" (Beta 14.0-148fccd) by shanapu
  46 "MyJailbreak - Warden" (Beta 14.0-148fccd) by shanapu
  47 "MyJailbreak - Weapons" (Beta 14.0-148fccd) by shanapu
  48 "MyJailbreak - Zeus" (Beta 14.0-148fccd) by shanapu
  49 "MyJailbreak - Zombie" (Beta 14.0-148fccd) by shanapu
  50 "MyJailShop" (1.5.0-4d2da1b) by shanapu
  51 "Blackout for MyJailShop" (1.0) by shanapu
  52 "ViewDoor for MyJailShop" (1.0) by shanapu
  53 "Freeday for MyJailShop" (1.0) by shanapu
  54 "MyJailShop - Credits HUD" (1.0) by shanapu
  55 "Ice Grenade item for MyJailShop" (1.0) by shanapu
  56 "Jetpack for MyJailShop" (1.0) by shanapu, FrozDark & gubka
  57 "Jihad for MyJailShop" (1.0) by shanapu
  58 "Parachute for MyJailShop" (1.0) by shanapu, zipcore
  59 "Nextmap" (1.10.0.6461) by AlliedModders LLC
  60 "Player Commands" (1.10.0.6461) by AlliedModders LLC
  61 "Reserved Slots" (1.10.0.6461) by AlliedModders LLC
  62 "Smart Jail Doors" (0.5.2-beta) by Maxim 'Kailo' Telezhenko
  63 "SM_Hosties v2" (2.2.0) by databomb & dataviruset & comando
  64 "Sound Commands" (1.10.0.6461) by AlliedModders LLC
  65 "Store - The Resurrection" (2.3.598) by Kyle`

**Comment by Kxnrl** [comment]
bad string meaning u have wrong model in database.
