### ISSUE TITLE
Doesn't work following the instructions.

### ISSUE THREAD

**Issue by Ancho-R** [Kxnrl/Store#12]
按照说明来安装，进游戏后输入!store后没有反应。。控制台输入sm_store也没反应。。
还需要安装别的什么插件吗，比如cg_core/zephstore这些的。。
数据库也导入连接成功了。。localhost
使用的版本是  /Store/master/1.8/286-master-ec83b9e.7z

提示：Exception reported: Can not retrieve item.parent from database: Lost connection to MySQL server during query
重试了好几遍qwq

**Comment by Ancho-R** [comment]
对了 还有 plugins 文件夹下有 store_jb/store_mg 这些，是只放一个进去还是全都要放进去。。
只想开个mg的服务器玩一玩_(:зゝ∠)_

**Comment by Kxnrl** [comment]
连接数据库的链接不稳,你表里有东西吗

**Comment by Ancho-R** [comment]
有，导入了之前一个issue里面你发的sql语句。。试了好几次都提醒失去连接。

**Comment by Ancho-R** [comment]
添加成功了，但是里面只有：人物装饰品、特效/颜色/喷漆、足迹/光环/霓虹、其他服务四个选项。。。没有人物模型。

**Comment by Ancho-R** [comment]
没有死亡音效_(:зゝ∠)_
老大怎么开启呀qwq

**Comment by Kxnrl** [comment]
文件放进去就行了.MP3格式的.文件不能是网易云那种带DRM的,不然会没法播放
