### ISSUE TITLE
The menu is not opening in-game.

### ISSUE THREAD

**Issue by ToPGameSyoutube** [Kxnrl/Store#123]
The hole plugin is correctly setup up.
But in-game it says that : [Store] Inventory loaded. Type !store  to open store menu.
But you can't actually open it.
What's the issue?

**Comment by Kxnrl** [comment]
Did you import item data into db?

**Comment by nyambaatar** [comment]
> Did you import item data into db?

how import item data into db 
all files download and installed server plugins. Not error log but show store menu. Pls help me

**Comment by Kxnrl** [comment]
Did you read the readme?
