### ISSUE TITLE
!store not work

### ISSUE THREAD

**Issue by greenhaha** [Kxnrl/Store#124]
数据表已经初始化了 但是 在游戏中 使用！store 商店插件并没有工作  
服务器后台 显示 下面错误  请问 这个是什么问题 该如何解决 谢谢大佬 ：）
L 03/07/2020 - 01:53:24: [SM] Exception reported: Can not retrieve item.parent from database: no result row
L 03/07/2020 - 01:53:24: [SM] Blaming: store.smx
L 03/07/2020 - 01:53:24: [SM] Call stack trace:
L 03/07/2020 - 01:53:24: [SM]   [0] SetFailState
L 03/07/2020 - 01:53:24: [SM]   [1] Line 3373, addons/sourcemod/scripting/store.sp::SQL_LoadParents

![image](https://user-images.githubusercontent.com/42140733/76109626-c8f16900-6017-11ea-849a-43c66f545f9f.png)

**Comment by Kxnrl** [comment]
需要先导入数据

**Comment by greenhaha** [comment]
没发现数据文件  表都创建了  但是数据文件没看到

**Comment by Kxnrl** [comment]
你是新装的还是从zpeh商店升级上来的

**Comment by greenhaha** [comment]
新装

**Comment by Kxnrl** [comment]
那你商店的物品当然得你自己添加啊........

**Comment by greenhaha** [comment]
大佬  我问一下  那个 导入数据的php文件 该怎么执行  看readme 没看懂   
Import parent data to your database. ( exec: php insertParent.php or goto: yourwebserver/insertParent.php )
Import item data to your database. ( exec: php insertItem.php or goto: yourwebserver/insertItem.php )
Check item validate ( exec: php loaditem.php or goto: yourwebserver/loaditem.php )

我在后台 utils文件夹下执行  php  insertItem.php
提示文件不存在  执行其他php文件报相同问题

![image](https://user-images.githubusercontent.com/42140733/76140385-def13f00-6094-11ea-942e-5b73a014c9bb.png)
 该如何解决

**Comment by Kxnrl** [comment]
php的脚本是升级上来的用的, 全新安装的要么你在sql管理工具手动加自己的数据, 要么用additem或者addparent里面的sql模板执行sql语句

**Comment by greenhaha** [comment]
thx ：）
