### ISSUE TITLE
店铺菜单无法打开

### ISSUE THREAD

**Issue by greenhaha** [Kxnrl/Store#126]
店铺菜单无法打开 后台log直至输入下面内容
L 03/23/2020 - 21:46:28: [SM] Call stack trace:
L 03/23/2020 - 21:46:28: [SM]   [0] ConVar.GetString
L 03/23/2020 - 21:46:28: [SM]   [1] Line 154, store/tpmode.sp::CheckClientTP
L 03/23/2020 - 21:46:28: [SM]   [2] Line 175, store/tpmode.sp::Timer_RepeatCheckTP
L 03/23/2020 - 21:46:28: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 03/23/2020 - 21:46:28: [SM] Blaming: store.smx
L 03/23/2020 - 21:50:12: Failed to connect to SQL database. [001] Error: Could not find driver "mysql"
L 03/23/2020 - 21:50:17: Failed to connect to SQL database. [001] Error: Could not find driver "mysql"
L 03/23/2020 - 21:50:22: Failed to connect to SQL database. [001] Error: Could not find driver "mysql"

数据库已经导入数据  导入数据的php文件已经执行了 
请问大佬该怎么解决

**Comment by Kxnrl** [comment]
apt-get install lib32z1
