### ISSUE TITLE
添加store plugin 启动服务器一直崩溃

### ISSUE THREAD

**Issue by greenhaha** [Kxnrl/Store#129]
系统：centos 7
商店插件： store_mg.smx => store.smx (重新命名)
服务器一直重启 

去掉商店插件后可以正常启动服务器 
控制台一直输出：

Host_Error: Bad string:

PreMinidumpCallback: updating dump comment
crash_20200405183620_1.dmp[30578]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200405183620_1.dmp
crash_20200405183620_1.dmp[30578]: Finished uploading minidump (out-of-process): success = no
crash_20200405183620_1.dmp[30578]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20200405183620_1.dmp[30578]: file ''/tmp/dumps/crash_20200405183620_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
./srcds_run: line 318: 30529 Segmentation fault      (core dumped) $HL_CMD
cat: hlds.30266.pid: No such file or directory

log文件：
L 04/05/2020 - 18:04:29: -------- Mapchange to de_dust2 --------
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "mapcyclefile") (value "map_custom1.txt")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "mp_tagging_scale") (value "100.0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_ms") (value "0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_ms_vgui") (value "0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_postgame_delay") (value "0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_when_empty") (value "0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_enablebunnyhopping") (value "0")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "phys_pushscale") (value "1")
L 04/05/2020 - 18:04:29: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "phys_timescale") (value "1")
L 04/05/2020 - 18:04:52: SourceMod log file session started (file "/home/steam/steamcmd/csgo/csgo/addons/sourcemod/logs/L20200405.log") (Version "1.11.0.6481")
L 04/05/2020 - 18:04:52: [store.smx] Force reload map to prevent server crash!
L 04/05/2020 - 18:04:52: [SM] Changed map to "de_dust2"

没有生成任何错误日志

已安装插件列表（plugins list）：

 "Fun Commands" (1.11.0.6481) by AlliedModders LLC
 "Basic Comm Control" (1.11.0.6481) by AlliedModders LLC
 "Basic Votes" (1.11.0.6481) by AlliedModders LLC
 "Client Preferences" (1.11.0.6481) by AlliedModders LLC
 "Basic Commands" (1.11.0.6481) by AlliedModders LLC
 "Basic Info Triggers" (1.11.0.6481) by AlliedModders LLC
 "Basic Chat" (1.11.0.6481) by AlliedModders LLC
 "Admin Help" (1.11.0.6481) by AlliedModders LLC
 "Fun Votes" (1.11.0.6481) by AlliedModders LLC
 "Nextmap" (1.11.0.6481) by AlliedModders LLC
 "Reserved Slots" (1.11.0.6481) by AlliedModders LLC
 "Anti-Flood" (1.11.0.6481) by AlliedModders LLC
 "Sound Commands" (1.11.0.6481) by AlliedModders LLC
 "Basic Ban Commands" (1.11.0.6481) by AlliedModders LLC
 "Admin File Reader" (1.11.0.6481) by AlliedModders LLC
 "Admin Menu" (1.11.0.6481) by AlliedModders LLC
 "Player Commands" (1.11.0.6481) by AlliedModders LLC

扩展列表（extensions）：
bintools.ext.so
clientprefs.ext.so
dbi.mysql.ext.so
dbi.sqlite.ext.so
game.cstrike.ext.2.csgo.so
game.cstrike.ext.2.css.so
game.tf2.ext.2.tf2.so
geoip.ext.so
PTaH.ext.2.csgo.so
regex.ext.so
sdkhooks.ext.2.blade.so
sdkhooks.ext.2.bms.so
sdkhooks.ext.2.csgo.so
sdkhooks.ext.2.css.so
sdkhooks.ext.2.dods.so
sdkhooks.ext.2.doi.so
sdkhooks.ext.2.ep1.so
sdkhooks.ext.2.ep2.so
sdkhooks.ext.2.hl2dm.so
sdkhooks.ext.2.insurgency.so
sdkhooks.ext.2.l4d.so
sdkhooks.ext.2.l4d2.so
sdkhooks.ext.2.nd.so
sdkhooks.ext.2.sdk2013.so
sdkhooks.ext.2.tf2.so
sdktools.ext.2.blade.so
sdktools.ext.2.bms.so
sdktools.ext.2.csgo.so
sdktools.ext.2.css.so
sdktools.ext.2.dods.so
sdktools.ext.2.doi.so
sdktools.ext.2.ep1.so
sdktools.ext.2.ep2.so
sdktools.ext.2.hl2dm.so
sdktools.ext.2.insurgency.so
sdktools.ext.2.l4d.so
sdktools.ext.2.l4d2.so
sdktools.ext.2.nd.so
sdktools.ext.2.sdk2013.so
sdktools.ext.2.tf2.so
topmenus.ext.so
updater.ext.so
webternet.ext.so

soucemod版本 
SourceMod 1.11.0.6481, by AlliedModders LLC

**Comment by Kxnrl** [comment]
你数据库导入了吗, 如果导入了检查一下试不试有什么非法模型.

**Comment by greenhaha** [comment]
全部导入了 并且执行了  php loaditem.php  没有发现任何问题 
导入的文件就是 store插件里自带的 item.txt 文件

**Comment by Kxnrl** [comment]
Host_Error: Bad string: 大概率是你在商店数据库中使用了非法的模型, 尝试删除一些从数据库

**Comment by greenhaha** [comment]
谢谢你 已经解决了 是粒子效果和光环的事
