### ISSUE TITLE
Can`t install store plugin on server

### ISSUE THREAD

**Issue by GH05T20** [Kxnrl/Store#13]
When, i upload all files on my server, configure databeses.cfg and addon database on my database hosting i heve problem. Plugin addon player with 300 credits to database when i type sm_credits i heve info about you heve 300 credits. When i type sm_store i don`t heve any reply :( 
In logs i don`t heve any errors :( 
Can you help my? I can for give you item.txt with polish translation when i translate it, it will be soon
 
BTW: additem.sql heve typo giftablle not giftable

**Comment by GH05T20** [comment]
I add all manualy, only game tags, textcolor and name kolors. Another I delete, i don`t need this.

**Comment by Kxnrl** [comment]
can u export your 2 sql tables and show to me ?

**Comment by GH05T20** [comment]
https://pastebin.com/1D9gj1GV and items.txt

**Comment by Kxnrl** [comment]
okay. i will test and fix if has bug.

**Comment by GH05T20** [comment]
really
thank you

**Comment by Kxnrl** [comment]
item`s parent is wrong id.

**Comment by Kxnrl** [comment]
``` SQL
-- Fix wrong parent
UPDATE store_item_child SET `parent` = 1 WHERE `type` = 'nametag';
UPDATE store_item_child SET `parent` = 2 WHERE `type` = 'namecolor';
UPDATE store_item_child SET `parent` = 3 WHERE `type` = 'msgcolor';

-- Fix wrong item attributes
UPDATE store_item_child SET `only` = 0, `vip` = 0;
UPDATE store_item_child SET `tag` = `color` WHERE `type` = 'nametag';  -- Fix bug , Wrong script u used.
```
It will work.

**Comment by Kxnrl** [comment]
``` SQL
-- Fix wrong parent id
truncate table `store_item_parent`;
INSERT INTO `store_item_parent` (`id`,`name`,`parent`) VALUES (0,'Tag',-1),(1,'Kolor Nicku',-1),(2,'Kolor Wiadomosci',-1);

-- Fix wrong parent
UPDATE store_item_child SET `parent` = 0 WHERE `type` = 'nametag';
UPDATE store_item_child SET `parent` = 1 WHERE `type` = 'namecolor';
UPDATE store_item_child SET `parent` = 2 WHERE `type` = 'msgcolor';

-- Fix wrong item attributes
UPDATE store_item_child SET `only` = 0, `vip` = 0;
-- your item name not set. u need set it in database

-- Fix bug , Wrong script u used.
UPDATE store_item_child SET `tag` = `color` WHERE `type` = 'nametag';  
```

### correct store_item_parent should be here.
![qq 20180608011752](https://user-images.githubusercontent.com/3905845/41115342-c77b0db0-6ab9-11e8-9d3a-4385a0fa9d3b.jpg)

## screenshots
![qq 20180608011637](https://user-images.githubusercontent.com/3905845/41115290-a6595100-6ab9-11e8-8b63-41c17551c0d5.jpg)
![qq 20180608011607](https://user-images.githubusercontent.com/3905845/41115292-a743d31a-6ab9-11e8-8fc1-6056cb138285.jpg)

**Comment by GH05T20** [comment]
Yes, it works, You are my GOD

**Comment by GH05T20** [comment]
Sorry for 1 more problem, which one i must put in on serwer Arena 1vs1. I don`t knew how to earn credits. And how to turn off gift 300 credits on start ;/ I`m so stupid ;/

**Comment by Kxnrl** [comment]
``` sourcepawn
            FormatEx(STRING(m_szQuery), "INSERT INTO store_players (`authid`, `name`, `credits`, `date_of_join`, `date_of_last_join`, `ban`) VALUES(\"%s\", '%s', 300, %d, %d, '0')", g_eClients[client][szAuthId], m_szEName, m_iTime, m_iTime);
```
change to 
``` sourcepawn
            FormatEx(STRING(m_szQuery), "INSERT INTO store_players (`authid`, `name`, `credits`, `date_of_join`, `date_of_last_join`, `ban`) VALUES(\"%s\", '%s', 0, %d, %d, '0')", g_eClients[client][szAuthId], m_szEName, m_iTime, m_iTime);
```
