### ISSUE TITLE
请问 如何设置 玩家获得积分

### ISSUE THREAD

**Issue by greenhaha** [Kxnrl/Store#131]
如何设置商店获得积分 例如：每分钟存活 获得2积分  杀死一人获得4积分 等 
在readme 文件里没有看到 相关游戏积分设置 
希望大佬能告诉菜鸟一下 谢谢了：）

也希望 大佬能提供一下  关于停止地图背景音乐的linux插件

**Comment by Kxnrl** [comment]
store.sp 里面搜索 option
