### ISSUE TITLE
!store command not working.

### ISSUE THREAD

**Issue by breno-star** [Kxnrl/Store#132]
When i type !store nothing happens, no error logs, please help.

![Screenshot_13](https://user-images.githubusercontent.com/63379518/78846515-68709580-79e2-11ea-9d07-2f54da5b8dc6.png)

**Comment by greenhaha** [comment]
maybe you do not  import data  check your mysql database
if you do not import data  you have to run php file. you can find some thing in readme file

**Comment by Kxnrl** [comment]
Did you import items data?

**Comment by breno-star** [comment]
How can i do that?

**Comment by Kxnrl** [comment]
import from items.txt or import manually

**Comment by breno-star** [comment]
I made the import but server is crashing with this message: **Host_Error Bad String**

Only have the store plugin.

**Comment by Kxnrl** [comment]
check u may import invalid model/aura/particle/trail model.
that made srcds crash

**Comment by breno-star** [comment]
I imported the **items.txt** that already came in the download file

**Comment by Kxnrl** [comment]
so server crash when player join?

**Comment by breno-star** [comment]
when player join

**Comment by Kxnrl** [comment]
99%  there are invalid model/particles/aura in your item database.

**Comment by Kxnrl** [comment]
try delete some items

**Comment by breno-star** [comment]
Ok, that's right? 
![Screenshot_6](https://user-images.githubusercontent.com/63379518/79088472-19479f00-7d19-11ea-8378-cd2dc09f7baa.png)

**Comment by breno-star** [comment]
I delete some items on items.txt but got the same error, check the file
[items.txt](https://github.com/Kxnrl/Store/files/4467843/items.txt)

Print of **store_items_child**

![Screenshot_7](https://user-images.githubusercontent.com/63379518/79089449-91fc2a80-7d1c-11ea-8c6f-fd3d904590ff.png)

Print of **store_items_parent**

![Screenshot_8](https://user-images.githubusercontent.com/63379518/79089480-adffcc00-7d1c-11ea-8add-66bad5445bf3.png)

**Comment by Kxnrl** [comment]
try disable some module in store.sp?
