### ISSUE TITLE
Problem with menu IG

### ISSUE THREAD

**Issue by ruinedmoon** [Kxnrl/Store#134]
When i try to use your "items.txt" my server just wont start, i got only restarts, but when i set only 1 model in items.txt with chinesee letters, IG i got some symbols like a|eaf;2o\, how can I fix that ?

or how can i use your items.txt ?

**Comment by ruinedmoon** [comment]
L 04/10/2020 - 20:42:36: [store.smx] Lock Convar [mp_match_restart_delay] to 20.0, from [10] to [20.000000].
L 04/10/2020 - 20:42:36: [store.smx] Lock Convar [mp_match_restart_delay] to 20.0, from [20.000000] to [10].
L 04/10/2020 - 20:42:36: [store.smx] Force reload map to prevent server crash!
L 04/10/2020 - 20:42:36: [SM] Changed map to "surf_lullaby_ksf"


That's from LOG when i try to start server with your items.txt

**Comment by Kxnrl** [comment]
try save as UTF8

**Comment by ruinedmoon** [comment]
I just download your txt file and imput him via script you made and i got same thing

**Comment by Kxnrl** [comment]
u run csgo on mac?

**Comment by ruinedmoon** [comment]
Nope, when i try to connect on other servers with your plugin i can see chineese symbols.
in phpmyadmin, database collation is utf8mb4_general_ci
But there are not cihneese symbols, there are "a|eaf;2o" things too...

**Comment by Kxnrl** [comment]
emm. maybe something went wrong while import
