### ISSUE TITLE
kxnrl please add english support

### ISSUE THREAD

**Issue by blastmod9999** [Kxnrl/Store#135]
please if you have gimme the translation of items.txt love you 3>

**Comment by Kxnrl** [comment]
items.txt is no needed. you should import your items.txt data into mysql database.

**Comment by blastmod9999** [comment]
How can i import mine

**Comment by blastmod9999** [comment]
Cuz i want to import the zeph store ones

**Comment by blastmod9999** [comment]
And i already installed yours

**Comment by Kxnrl** [comment]
...
clean items/parent table. 
re-import your items.txt via php script
