### ISSUE TITLE
Categories not working and insertitem.php error, pls help.

### ISSUE THREAD

**Issue by cleber1337** [Kxnrl/Store#137]
Hello, I followed the plugin installation tutorial but some things did not work out very well, as you can see in the screenshot only 2 categories are appearing and the items.txt file has more ...
![Screenshot_24](https://user-images.githubusercontent.com/64625663/80779965-9eb5b680-8b43-11ea-86db-630780e9be3e.png)

Items.txt file:
[items.txt](https://github.com/Kxnrl/Store/files/4562405/items.txt)

InsertItem.php error:
![Screenshot_25](https://user-images.githubusercontent.com/64625663/80779990-abd2a580-8b43-11ea-8151-f722ad2c4243.png)

Database screenshots:
![Screenshot_26](https://user-images.githubusercontent.com/64625663/80779976-a5442e00-8b43-11ea-82d0-03ce56e6a311.png)
![Screenshot_27](https://user-images.githubusercontent.com/64625663/80779978-a6755b00-8b43-11ea-947e-2de170766354.png)

**Comment by Kxnrl** [comment]
can u share items.txt

**Comment by cleber1337** [comment]
is on the first post: https://github.com/Kxnrl/Store/files/4562405/items.txt

**Comment by cleber1337** [comment]
pls help

**Comment by Kxnrl** [comment]
look like some lines broke the kv parser.
can u try add item manually?

**Comment by cleber1337** [comment]
thats a lot of work but i gonna try.

**Comment by cleber1337** [comment]
Okay, I added the items manually, but my server is crashing with an error called: `Host_Error: Bad String`

Here is my items.txt
[items.txt](https://github.com/Kxnrl/Store/files/4596065/items.txt)

Screenshot of store_item_child
![Screenshot_31](https://user-images.githubusercontent.com/64625663/81350117-a8856f80-9097-11ea-8872-626334901ac4.png)

Screenshot of store_item_parent
![Screenshot_32](https://user-images.githubusercontent.com/64625663/81350121-aae7c980-9097-11ea-888f-eaf8e6636adc.png)

Screenshot of error:
![Screenshot_30](https://user-images.githubusercontent.com/64625663/81350195-c7840180-9097-11ea-9910-7c68bafaec41.png)


Please help

**Comment by Kxnrl** [comment]
can u export item?

**Comment by Kxnrl** [comment]
Bad string with null meaning u have itme that has no model path.

**Comment by cleber1337** [comment]
Thank you for your support! The problem was that I had forgotten to upload some models. Now everything is working!
