### ISSUE TITLE
Problem with buying the service (store)

### ISSUE THREAD

**Issue by blady334** [Kxnrl/Store#142]
HI, 
I have problem with buying the service for a month if I already bought the same service for only one day.

Error log:
Query: INSERT INTO store_items (`player_id`, `type`, `unique_id`, `date_of_purchase`, `date_of_expiration`, `price_of_purchase`) VALUES(270, "namecolor", "namecolor_rainbow", 1589468047, 1592060047, 5000)
Error: Duplicate entry '270-namecolor-namecolor_rainbow' for key 'p'

**Comment by Kxnrl** [comment]
can not extend item expiration time  via purchase menu.
so if you already have that item, can not buy anymore

**Comment by blady334** [comment]
Yes, I agree, but there is no such blockade. Despite the fact that he has this service, he can still buy it. When he buys this service, he takes his credits but no longer adds or extends his service.

**Comment by Kxnrl** [comment]
no , i think something went wrong, if you already have that item, purchase menu will not display, just display equipment menu.

**Comment by blady334** [comment]
I understand, why did I see such an error? The player took the credits but the service was no longer extended.

**Comment by Kxnrl** [comment]
the lastest master build may fix it.
