### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by cleber1337** [Kxnrl/Store#143]
Hello, I would like to know if it is possible to disable this Compose system, I am trying to buy items but it always says that I do not have enough compost materials, I would like it to be just a normal credit purchase system

**Comment by Kxnrl** [comment]
set item attr 'compose' to 0

**Comment by cleber1337** [comment]
playerskin still unable to buy

**Comment by Kxnrl** [comment]
Did you set buyable to 1 and keep only to 0 and auth is 'ITEM_NO_PERSONAL'

**Comment by cleber1337** [comment]
I changed it to 'ITEM_NO_PERSONAL' but still can't buy, look at the screenshots
![Screenshot_12](https://user-images.githubusercontent.com/64625663/82398728-e2f0f400-9a29-11ea-87af-e2b4fd035769.png)
![Screenshot_13](https://user-images.githubusercontent.com/64625663/82398736-e5ebe480-9a29-11ea-9b08-ccd388bd489f.png)
![awp_lego_midnight_str0001](https://user-images.githubusercontent.com/64625663/82398755-f2703d00-9a29-11ea-9dba-b640b280f675.jpg)

**Comment by cleber1337** [comment]
so?

**Comment by Kxnrl** [comment]
emm, why u change the file. all item attributes in mysql database.

**Comment by Kxnrl** [comment]
set the `only` to 0

**Comment by Kxnrl** [comment]
set the `case` to -1
