### ISSUE TITLE
Store.smx

### ISSUE THREAD

**Issue by PJC1019** [Kxnrl/Store#145]
Hey, how i can fix it?
L 05/30/2020 - 18:15:08: [SM] Call stack trace:
L 05/30/2020 - 18:15:08: [SM]   [0] ConVar.GetString
L 05/30/2020 - 18:15:08: [SM]   [1] Line 154, store/tpmode.sp::CheckClientTP
L 05/30/2020 - 18:15:08: [SM]   [2] Line 175, store/tpmode.sp::Timer_RepeatCheckTP
L 05/30/2020 - 18:15:08: [SM] Exception reported: Invalid convar handle 0 (error 4)

**Comment by Kxnrl** [comment]
Fixed

**Comment by PJC1019** [comment]
Still :s

**Comment by Kxnrl** [comment]
what version u use?

**Comment by PJC1019** [comment]
663 ver

**Comment by Kxnrl** [comment]
store file name?

**Comment by PJC1019** [comment]
hz.
Which is stable?

**Comment by Kxnrl** [comment]
no, e.g. store_jb.smx or compiled by urself

**Comment by PJC1019** [comment]
store_jb.smx didn't work...

**Comment by Kxnrl** [comment]
no , so i mean what version u used before.

**Comment by PJC1019** [comment]
I was using store_hz.smx

**Comment by Kxnrl** [comment]
can u share the 663 ver errlogs?

**Comment by PJC1019** [comment]
Sure.
[errors_20200617.log](https://github.com/Kxnrl/Store/files/4791770/errors_20200617.log)

**Comment by Kxnrl** [comment]
I don't know why cvar mp_forcecamera does not exists on your server

**Comment by PJC1019** [comment]
it's a test server, there is just sourcemode 1.10 and your store.

**Comment by Kxnrl** [comment]
try 664 master

**Comment by PJC1019** [comment]
Same...
L 06/17/2020 - 12:38:18: [SM] Blaming: store.smx
L 06/17/2020 - 12:38:18: [SM] Call stack trace:
L 06/17/2020 - 12:38:18: [SM] [0] ConVar.GetString
L 06/17/2020 - 12:38:18: [SM] [1] Line 154, store/tpmode.sp::CheckClientTP
L 06/17/2020 - 12:38:18: [SM] [2] Line 175, store/tpmode.sp::Timer_RepeatCheckTP

**Comment by PJC1019** [comment]
Ok, now i haven't this logs but, i have this XD
L 06/17/2020 - 12:54:26: [SM] Exception reported: Can not retrieve item.parent from database: no result row
L 06/17/2020 - 12:54:26: [SM] Blaming: store.smx
L 06/17/2020 - 12:54:26: [SM] Call stack trace:
L 06/17/2020 - 12:54:26: [SM] [0] SetFailState
L 06/17/2020 - 12:54:26: [SM] [1] Line 3532, addons/sourcemod/scripting/store.sp::SQL_LoadParents
PutClientInServer: no info_player_start on level

**Comment by Kxnrl** [comment]
Import item data before server start
