### ISSUE TITLE
Issue & Question

### ISSUE THREAD

**Issue by qNope7** [Kxnrl/Store#146]
1. L 06/07/2020 - 19:34:10: [SM] Exception reported: Can not retrieve item.parent from database: no result row
L 06/07/2020 - 19:34:10: [SM] Blaming: store.smx
L 06/07/2020 - 19:34:10: [SM] Call stack trace:
L 06/07/2020 - 19:34:10: [SM]   [0] SetFailState
L 06/07/2020 - 19:34:10: [SM]   [1] Line 3530, addons/sourcemod/scripting/store.sp::SQL_LoadParents

2. This https://forums.alliedmods.net/showpost.php?p=2377630&postcount=80 will work on this store version?

**Comment by Kxnrl** [comment]
1. import items before start server.
2. custom models is built-in module.

**Comment by qNope7** [comment]
How i can import items?
( i'm not upgrading from zephyrus store )

**Comment by Kxnrl** [comment]
If u using phpmyadmin, just adding row into store_item_child and store_item_parent
