### ISSUE TITLE
Question - How do users gain credits?

### ISSUE THREAD

**Issue by stunslave** [Kxnrl/Store#147]
I would like to know how users are meant to gain credits when using store_sr or store_hz... 
I have tested quite a lot I haven't found how to gain credits without actually giving out credits. 

Killing players or being active does not give players credits.

**Comment by Kxnrl** [comment]
store has built-in function to give online credits, if you want to killing players credits, you should make 3rd-party plugin and call native Store_SetClientCredits

**Comment by stunslave** [comment]
Is there's away to gain credits over time. (Time played) 
What do I need to change to get this to work?

**Comment by Kxnrl** [comment]
You need change options in store.sp
