### ISSUE TITLE
database table store_players has invalid column type for dates ?

### ISSUE THREAD

**Issue by Nycrera** [Kxnrl/Store#148]
Hello,
I am assuming that the plugin adds new players to the database table "store_players".
But while doing so clients get kicked with the following message:
<Failed to check your store account.>
this happens for all of the players/clients.

On server logs I get this error / debug message:
"Error happened. Error: Out of range value for column 'date_of_join' at row 1"

I assumed that INT(11) was problematic for a date and changed the column type of 'date_of_join' and 'date_of_last_join' to VARCHAR(20) which solved the problem. I just wanted to inform you about this bug.

But then I still couldn't get it working anyway. This time clients were able to join the server with no problem but the command sm_store didn't produce any errors on server-side and nothing happens, basically.

Here you can find my loaditem.php dump: [https://hastebin.com/raw/sevaqefife](https://hastebin.com/raw/sevaqefife)

This is a fresh install. I added one parent and one item (weaponskin knife) for testing purposes with given SQL scripts.
Any help is welcome.

**Comment by Kxnrl** [comment]
stable or master?

**Comment by Nycrera** [comment]
stable.

**Comment by ApollonV2K** [comment]
@Kxnrl I just installed the plugin and I get this error. Do you have a solution?

**Comment by Kxnrl** [comment]
try master
