### ISSUE TITLE
VIP Flags

### ISSUE THREAD

**Issue by MarshGOD** [Kxnrl/Store#151]
Ah, im using this store for the first time, been using zeph store for a long time and im shifting to this store.
I have installed store items properly and they are working but i wanna know how the VIP System works in this store.
I want to make some items VIP Exclusive only, Anyone kind enough yo guide me through that.

**Comment by Kxnrl** [comment]
if set vip to 1, all price filed to 0, item free for all vip players.
if set vip to 1, and price, item can be purchased by vip players only.

**Comment by MarshGOD** [comment]
Thank you!

**Comment by MarshGOD** [comment]
There is 1 more doubt that i have @Kxnrl 
When someone dies theres a first person death effect, like they die in first person.
I think its from the store and dont see an option to disable that, Can you guide me about it.

**Comment by MarshGOD** [comment]
nvm, figured it out.
