### ISSUE TITLE
Can not retrieve item.parent from database: no result row

### ISSUE THREAD

**Issue by LucasJX** [Kxnrl/Store#161]
Can not retrieve item.parent from database: no result row
![微信截图_20210507104722](https://user-images.githubusercontent.com/50724432/117391007-b88d9480-af21-11eb-8f7c-ea7618e305cc.png)
![微信截图_20210507104758](https://user-images.githubusercontent.com/50724432/117391012-ba575800-af21-11eb-9da4-89786dd0939c.png)

**Comment by LucasJX** [comment]
![image](https://user-images.githubusercontent.com/50724432/118452114-738b0e80-b728-11eb-9fae-f4869b849619.png)
这样设置后还是没有任何商品。
![image](https://user-images.githubusercontent.com/50724432/118452194-830a5780-b728-11eb-8df2-555cf01b26e1.png)

**Comment by Kxnrl** [comment]
> ![image](https://user-images.githubusercontent.com/50724432/118452114-738b0e80-b728-11eb-9fae-f4869b849619.png)
> 这样设置后还是没有任何商品。
> ![image](https://user-images.githubusercontent.com/50724432/118452194-830a5780-b728-11eb-8df2-555cf01b26e1.png)

你写错了

**Comment by LucasJX** [comment]
> > ![image](https://user-images.githubusercontent.com/50724432/118452114-738b0e80-b728-11eb-9fae-f4869b849619.png)
> > 这样设置后还是没有任何商品。
> > ![image](https://user-images.githubusercontent.com/50724432/118452194-830a5780-b728-11eb-8df2-555cf01b26e1.png)
> 
> 你写错了

是的，我根据文件里的内容修改了数据库。但是修改好后，在游戏里依然无法打开。显示未上架商品。
![QQ截图20210520115701](https://user-images.githubusercontent.com/50724432/118917066-a7517880-b962-11eb-8e6e-e365b570b540.jpg)
![QQ截图20210520115711](https://user-images.githubusercontent.com/50724432/118917071-a91b3c00-b962-11eb-92c5-9bcce268e5f4.jpg)
![微信图片_20210520115539](https://user-images.githubusercontent.com/50724432/118917075-aa4c6900-b962-11eb-9341-550543da641f.png)

**Comment by Kxnrl** [comment]
> > > ![image](https://user-images.githubusercontent.com/50724432/118452114-738b0e80-b728-11eb-9fae-f4869b849619.png)
> > > 这样设置后还是没有任何商品。
> > > ![image](https://user-images.githubusercontent.com/50724432/118452194-830a5780-b728-11eb-8df2-555cf01b26e1.png)
> > 
> > 
> > 你写错了
> 
> 是的，我根据文件里的内容修改了数据库。但是修改好后，在游戏里依然无法打开。显示未上架商品。
> ![QQ截图20210520115701](https://user-images.githubusercontent.com/50724432/118917066-a7517880-b962-11eb-8e6e-e365b570b540.jpg)
> ![QQ截图20210520115711](https://user-images.githubusercontent.com/50724432/118917071-a91b3c00-b962-11eb-92c5-9bcce268e5f4.jpg)
> ![微信图片_20210520115539](https://user-images.githubusercontent.com/50724432/118917075-aa4c6900-b962-11eb-9341-550543da641f.png)

那你服务器里放置了文件了吗

**Comment by LucasJX** [comment]
> > > > ![image](https://user-images.githubusercontent.com/50724432/118452114-738b0e80-b728-11eb-9fae-f4869b849619.png)
> > > > 这样设置后还是没有任何商品。
> > > > ![image](https://user-images.githubusercontent.com/50724432/118452194-830a5780-b728-11eb-8df2-555cf01b26e1.png)
> > > 
> > > 
> > > 你写错了
> > 
> > 
> > 是的，我根据文件里的内容修改了数据库。但是修改好后，在游戏里依然无法打开。显示未上架商品。
> > ![QQ截图20210520115701](https://user-images.githubusercontent.com/50724432/118917066-a7517880-b962-11eb-8e6e-e365b570b540.jpg)
> > ![QQ截图20210520115711](https://user-images.githubusercontent.com/50724432/118917071-a91b3c00-b962-11eb-92c5-9bcce268e5f4.jpg)
> > ![微信图片_20210520115539](https://user-images.githubusercontent.com/50724432/118917075-aa4c6900-b962-11eb-9341-550543da641f.png)
> 
> 那你服务器里放置了文件了吗

已经将人物模型丢进服务器了，然后下载了个SDownloader插件，设置好了下载路径，能够正常下载文件。但是一直显示无商品。

**Comment by Kxnrl** [comment]
确定下models字段的路径是否和实际路径完全匹配.
如果还不行, 打个日志吧

**Comment by LucasJX** [comment]
> 如果还不行, 打个日志吧

路径的话没有问题，我刚核对了一下。
日志我能在哪看，然后发你看看呢？
能直接发你服务器信息直接看吗，不是太懂。

**Comment by Kxnrl** [comment]
还有你store用的是哪个版本, 我指的是后缀, 还是说你自己编译的.

**Comment by LucasJX** [comment]
Store-SM1.10-latest.7z

--724-master-a29740c.7z

5月19日的版本

**Comment by Kxnrl** [comment]
我是说store里面有很多个版本, 不同后缀的smx启用的功能不一样 - -
![JX$54~8HB_9H3@`I4DY3@4I](https://user-images.githubusercontent.com/3905845/119360667-6c8e6e00-bcdd-11eb-9f62-c2d1edefa649.jpg)

**Comment by LucasJX** [comment]
噗嗤…(ಥ_ಥ)妈蛋
pr后缀改store
只是smx文件修改了后缀，其他文件未变，其余smx文件直接删除。
服务器一直是竞技模式。

**Comment by Kxnrl** [comment]
竞技模式不启用皮肤哦. 具体代码可以查看此处
https://github.com/Kxnrl/Store/blob/master/store.sp#L140-L180

**Comment by LucasJX** [comment]
咦，搞的我菊花一痛，不会编程的我明天挨着看看。
现在先找女朋友啪一下。

**Comment by LucasJX** [comment]
> 竞技模式不启用皮肤哦. 具体代码可以查看此处
> https://github.com/Kxnrl/Store/blob/master/store.sp#L140-L180

亲爱的，我搞定了哦。可以不用py交易了哦。
