### ISSUE TITLE
关于插件使用上的一点疑问。

### ISSUE THREAD

**Issue by LucasJX** [Kxnrl/Store#163]
关于视角的问题：
角色死亡后，会出现死亡视角。
但是按着键盘方向键或者空格键有一定几率出现自由视角。

关于积分问题：
插件可以根据在线时长获得积分。
但是在游玩中，只有进入服务器得了600的积分，过后一直没有出现增加积分。

赠送积分的问题：
指令：sm_givecredits <target> <amount>
输入指令：sm_givecredits <steam:32ID> <数量>
出现：[Store] 指定数量无效

**Comment by Kxnrl** [comment]
第一个是正常现象。
第二个是你命令参数使用不当

**Comment by LucasJX** [comment]
能在哪里设置关闭自由视角呢，固定住第一人称视角。

给予积分指令我输入的：sm_givecredits <steam:32ID> <数量>
我看提示写的也是：sm_givecredits <ID> <数量>

**Comment by Kxnrl** [comment]
> 一、能在哪里设置关闭第一人称死亡视角呢？
> 我在问题里搜索到了你的代码，但是不知道应该在哪个文件中添加。
> 
> ```
> public Action Store_OnFPDeathCamera(int client)
> {
>     if (something)
>     {
>         // block
>         return Plugin_Handled;
>     }
> 
>     return Plugin_Continue;
> }
> ```
> 
> 二、积分给与指令使用方法？
> 给予积分指令我输入的：`sm_givecredits <steam:32ID> <数量>`
> 我看提示写的也是：`sm_givecredits <ID> <数量>`

1.
store_firstperson_death_camera 0

2. 这设计基础的SM使用. 我都给你整无语了
如果你是#userid不需要引号包裹
比如``sm_givecredits  #4213 100``
如果你要STEAMID当然需要引号包裹了..
``sm_givecredits  "STEAM_1:1:1234" 100``
或者转义过的STEAMID
``sm_givecredits  STEAM_1_1_1234 100``
少玩游戏多看官方文档.
