### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Sacricx** [Kxnrl/Store#171]
Hey Kxnrl, 
I want to compile the store.sp against the latest stable build from sourcemod 1.10.
However I do recieve this errors on compile:

//// store.sp
//
// addons\sourcemod\scripting\include\store_stock.inc(7) : error 050: constant 'szName' already defined
// addons\sourcemod\scripting\include\store_stock.inc(40) : error 050: constant 'iId' already defined
// addons\sourcemod\scripting\include\store_stock.inc(59) : error 050: constant 'szPlFile' already defined
// addons\sourcemod\scripting\store.sp(45) : error 074: #define pattern must start with an alphabetic character
// addons\sourcemod\scripting\store.sp(514) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(518) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1285) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1285) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1288) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1398) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(1432) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1432) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1435) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(1987) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(1989) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(1991) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(2272) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(2272) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(2274) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(2295) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(2484) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(2484) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(2486) : error 032: array index out of bounds (variable "g_eMenuHandlers")
// addons\sourcemod\scripting\store.sp(3200) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(3730) : error 032: array index out of bounds (variable "g_ePlans")
// addons\sourcemod\scripting\store.sp(3738) : error 032: array index out of bounds (variable "g_ePlans")
//
// Compilation aborted.
// 26 Errors.

You're probably busy IRL but I want to show you this and ask if I probably missed something. 
I also had to add your public includes (fys.ops.inc & fys.pupd.inc) as the compiler asked for it on first compile. 
After adding those I was presented the errors from above.

Best Regards

Sacricx

**Comment by Kxnrl** [comment]
use latest tree

**Comment by Sacricx** [comment]
Thank you for your fast reply Kxnrl !
Infact using the master branch let me successfully compile against the latest stable SM build.
I really could have been smarter at this point >_>.

Thank you very much for your fast reply and help and thank you for providing and maintaining this store for us !

Best Regards

Sacricx
