### ISSUE TITLE
Add custom weapon shoot sound via hook weapon_fire

### ISSUE THREAD

**Issue by ronglucky** [Kxnrl/Store#172]
Hi can you add "sound" config for custom weapon model shooting sound. It would be great if you could add this feaure. Thank you

**Comment by Kxnrl** [comment]
weapon fire sound is prediction sound from client-side

**Comment by ronglucky** [comment]
no, I mean I play on some server I saw they have custom sound on the custom weapon of their store and I still hear the custom sound that play overlap the default one. I'm fine with that.
