### ISSUE TITLE
what is the GameMode mean?

### ISSUE THREAD

**Issue by GhostZhr1998** [Kxnrl/Store#181]
![image](https://user-images.githubusercontent.com/67358635/167361059-02b38b9b-7775-46ab-8018-ba44866e7cde.png)
I don't know the meaning of these game modes. I can't choose

**Comment by Kxnrl** [comment]
from map prefix, e.g. mg_mikis_multigames using _mg

**Comment by GhostZhr1998** [comment]
> mg_mikis_multigames

How do I choose files if I use different maps?
eg:
cs_office
de_dust2
