### ISSUE TITLE
Auras and Trails.

### ISSUE THREAD

**Issue by SlightofHand** [Kxnrl/Store#20]
All files download have the menu's for tails and auras, but they do not work, cant see trails or aura's in-game when bought and selected.. Any idea why it could be not working? (No errors in logs) (Neons work)

**Comment by Kxnrl** [comment]
Did you use our particles(.fx) and trails` file?

**Comment by SlightofHand** [comment]
What is says in console is " Attempting to create unknown particle system 'Trail5' " Whenever i try select a trail. Aura says "Attempting to create unknown particle system 'Aura8' "

**Comment by SlightofHand** [comment]
Using all your models/particles/marterials/sounds and .txt files. Everything downloads. Only trails/particles and aura's do not work in-game, everything else is perfect.

**Comment by Kxnrl** [comment]
I will check it. Can you tell me  your sourcemod version and OS?

**Comment by SlightofHand** [comment]
1.8.0.6048
Windows 10

**Comment by Kxnrl** [comment]
``` SQL
UPDATE `store_item_child` SET `model` = 'particles/FX.pcf' WHERE type = 'aura';
UPDATE `store_item_child` SET `model` = 'particles/FX.pcf' WHERE type = 'particle';
```
Run this sql command.

**Comment by SlightofHand** [comment]
UPDATE `store_item_child` SET `model` = 'particles/FX.pcf' WHERE type = 'aura'	10 row(s) affected Rows matched: 10  Changed: 10  Warnings: 0	0.125 sec
UPDATE `store_item_child` SET `model` = 'particles/FX.pcf' WHERE type = 'particle'	10 row(s) affected Rows matched: 10  Changed: 10  Warnings: 0	0.094 sec

Still gets these errors - 
Attempting to create unknown particle system 'Aura8' 
Attempting to create unknown particle system 'Trail5' 
Attempting to create unknown particle system 'Aura8' 
Attempting to create unknown particle system 'Trail5' 
Attempting to create unknown particle system 'Aura8' 
Attempting to create unknown particle system 'Trail5' 

Also now Gifting doesn't work tho. (was working previously)

L 06/26/2018 - 09:01:00: [SM] Call stack trace:
L 06/26/2018 - 09:01:00: [SM]   [1] Line 2791, addons/sourcemod/scripting/store.sp::UTIL_GiftItem
L 06/26/2018 - 09:01:00: [SM]   [2] Line 2078, addons/sourcemod/scripting/store.sp::MenuHandler_Gift
L 06/26/2018 - 09:01:00: [SM]   [4] Call_Finish
L 06/26/2018 - 09:01:00: [SM]   [5] Line 2136, addons/sourcemod/scripting/store.sp::MenuHandler_Confirm

**Comment by Kxnrl** [comment]
is there FX.pcf in your client? path Steam\steamapps\common\Counter-Strike Global Offensive\csgo\particles

**Comment by SlightofHand** [comment]
https://imgur.com/a/WlGYo2n - and all added to fastdl as bz2

**Comment by SlightofHand** [comment]
I found that only FX.pcf downloads, the rest do not in particles.

**Comment by Kxnrl** [comment]
for our resource. all in FX.pcf.  that include particle and aura.
