### ISSUE TITLE
!store Command not working

### ISSUE THREAD

**Issue by Valve-Anti-Cheat** [Kxnrl/Store#26]
Hi there,

I followed the installation step 1-to-1 but the store isn't working
I am using Sourcemod 1.9 and I downloaded the 1.9 413 build.
When I enter the command nothing happens 

Databases.cfg : https://pastebin.com/removed
Error Log : https://pastebin.com/cBCFwBN0

Any suggestions?

**Comment by Kxnrl** [comment]
my bad. u need install 1 store.smx. 
more info check readme

**Comment by Valve-Anti-Cheat** [comment]
Still not working, although there are a lot fewer errors, here it updated errors log: https://pastebin.com/eFhH81uh

**Comment by Kxnrl** [comment]
hey, u need to rename store_mg.smx to store.smx make library work

**Comment by Kxnrl** [comment]
look like travis-ci bugged. i will restart build job

**Comment by Kxnrl** [comment]
wait a few min and try to download https://build.kxnrl.com/Store/master/

**Comment by Valve-Anti-Cheat** [comment]
Downloaded and switched to 415, renamed to store.smx but still nothing, here is updated error log: https://pastebin.com/SHQZ0Ce7

Thanks for the quick replies and fast support x

**Comment by Kxnrl** [comment]
u need import your store items into your mysql database

**Comment by Kxnrl** [comment]
if u upgrade from zeph`store, just using our php scripts. if u are first time to use this store, u need manually import item and parent via our sql scripts.

**Comment by Valve-Anti-Cheat** [comment]
I'm not updating from Zeph store. Uhm, I would I do that? What file would I have to import? I already imported database.sql.

**Comment by Kxnrl** [comment]
scripts are in /utils folder, check addParent.sql and addItem.sql

**Comment by Valve-Anti-Cheat** [comment]
Yh saw that now, which tables do I import them into? addParent in store_items_child and addItem.sql in store_items?

**Comment by Valve-Anti-Cheat** [comment]
Ok, I have made progress. Seems to be working now. Butttt... I think something is broken x) https://gyazo.com/bbed2ed948eee7cadacaba4849c056b4

**Comment by Kxnrl** [comment]
seem like u import my items.txt or sql string?

**Comment by Cruze03** [comment]
@Valve-Anti-Cheat nice advert 😂😂😂

**Comment by Valve-Anti-Cheat** [comment]
@Kxnrl Mate I am having a really hard time installing this, been trying for a few days now. Could you help me fam.

https://steamcommunity.com/id/finnphp/
