### ISSUE TITLE
upgrade from Zephstore to this Store

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#27]
i have the problem when i use /insertitem.php 
If you want to see the items.txt add me on steam or i add you

this error:
Warning: array_key_exists() expects parameter 2 to be array, string given in /insertItem.php on line 35
Warning: Invalid argument supplied for foreach() in /insertItem.php on line 118

**Comment by Kxnrl** [comment]
can u share me your items.txt

**Comment by Caaine** [comment]
what is your steam name?
is this yours? https://steamcommunity.com/profiles/76561198048432253/

**Comment by Kxnrl** [comment]
yes.

**Comment by Caaine** [comment]
added you

**Comment by Kxnrl** [comment]
your name? 
![image](https://user-images.githubusercontent.com/3905845/48148000-b0722100-e2f3-11e8-91c3-4441fb2bf04a.png)

**Comment by Caaine** [comment]
Caaine
