### ISSUE TITLE
Invalid index -1 (count: 0)

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#31]
L 11/20/2018 - 19:45:18: [SM] Exception reported: Invalid index -1 (count: 0)
L 11/20/2018 - 19:45:18: [SM] Blaming: store.smx
L 11/20/2018 - 19:45:18: [SM] Call stack trace:
L 11/20/2018 - 19:45:18: [SM]   [0] ArrayList.GetString
L 11/20/2018 - 19:45:18: [SM]   [1] Line 1403, store.sp::Timer_OpeningCase

**Comment by Kxnrl** [comment]
Is this full stack trace?

**Comment by Caaine** [comment]
yes

**Comment by Kxnrl** [comment]
Fix in https://github.com/Kxnrl/Store/commit/dddafa0b9e43fd441d20fd53f87ac9f9e865ada0
