### ISSUE TITLE
Items not in the Inventory

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#34]
You have bought a Light Pink neon, you need equip that.

When go in the Inventory Pink neon is not in the Inventory
then buy a other neon, pink neon is in the Inventory the new item not.

in the mySQL > https://puu.sh/CfVCc/9ccc745c61.png "package"

**Comment by Kxnrl** [comment]
can you show me more info about your 'store_item_child' and 'store_item_parent' ?

**Comment by Caaine** [comment]
parent: https://puu.sh/Ch66Z/9b955b6bdf.png

https://puu.sh/Ch676/634d8aa4c3.png
https://puu.sh/Ch673/8b36fa2128.png
https://puu.sh/Ch678/ae4784ee0a.png

**Comment by Kxnrl** [comment]
Try this code

``` sourcepawn
public void Store_OnStoreAvailable(ArrayList item_name, ArrayList item_uid, ArrayList item_index, ArrayList item_level)
{
    char name[32];
    int uid, index, level;
    for(int x = 0; x < item_name.Length; ++x)
    {
        item_name.GetString(x, name, 32);
        uid = item_uid.Get(x);
        index = item_index.Get(x);
        level = item_level.Get(x);
        LogMessage("[Item Data]   [%s] %d:%d:%d", name, uid, index, level);
    }
}
```
