### ISSUE TITLE
neon hide

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#35]
neon hide not working
[Store] Hide trails / neon / aura ON now

https://steamuserimages-a.akamaihd.net/ugc/943965591836049151/0BBCF80908450E380C41FB1939DA71E7FA8A8FBA/

**Comment by Kxnrl** [comment]
tarils/ aura / particles still working?

**Comment by Caaine** [comment]
yes

**Comment by Saengerkrieg12** [comment]
`https://www.youtube.com/watch?v=yULWN4AOp04`
