### ISSUE TITLE
死亡音效播放代码有BUG

### ISSUE THREAD

**Issue by Illyasviels** [Kxnrl/Store#36]
在 modules/skin.sp 文件中
358/359 行：    
358: if(g_szDeathVoice[client][0] == '\0')
359: return Plugin_Continue;
中的 g_szDeathVoice 获取不到全局变量的值，始终为\0，所以无论模型是否存在死亡音效（数据库中），都会被 Plugin_Continue。

我的解决办法：
注释了这两句话，修改了下面的方法。
```
void Broadcast_DeathSound(int client)
{
    if(g_szDeathVoice[client][0] == '\0'){
        char DeathPath[255];
        FormatEx(DeathPath, 255, "~player/death%d.wav", GetRandomInt(1, 6));
        EmitSoundToAll(DeathPath, client);
        return;
    }

#if defined GM_ZE
    if(g_iClientTeam[client] == 2)
        return;
#endif

    float fPos[3];
    GetClientEyePosition(client, fPos);
    
    float fAgl[3];
    GetClientEyeAngles(client, fAgl);

    fPos[2] -= 3.0;

    // PrintToChatAll(g_szDeathVoice[client]);
    EmitSoundToAll(g_szDeathVoice[client], client);
    //EmitSoundToAll(g_szDeathVoice[client], client, SNDCHAN_VOICE, SNDLEVEL_NORMAL, SND_NOFLAGS, 0.5, SNDPITCH_NORMAL, client, fPos, fAgl, true);
}
```

**Comment by Kxnrl** [comment]
你用的版本号是多少的

**Comment by Kxnrl** [comment]
再就是这个 function Broadcast_DeathSound(int)
调用的地方是在 Event -> player_death -> Mode_Pre
所以正常的自杀音频是不会收到干扰的吧.
g_szDeathSound[] 这个赋值都是在设置模型的时候处理的
``` sourcepawn
public Action Event_PlayerDeath_Pre(Event event, const char[] name, bool dontBroadcast)
{
    int client = GetClientOfUserId(event.GetInt("userid"));

    if(IsFakeClient(client))
        return Plugin_Continue;

    Broadcast_DeathSound(client);
}
```

而sound hook只是处理了死亡的音频

**Comment by Illyasviels** [comment]
我用的是 1.9 - 455 的版本。

```
public Action Hook_NormalSound(){
    if(g_szDeathVoice[client][0] == '\0')
        return Plugin_Continue;
}
```
这个地方我用
` PrintToChatAll(g_szDeathVoice[client]); `
测试了一下，结果g_szDeathVoice[client]给的是空，所以不管装备的皮肤存不存在死亡音效都会出发 Plugin_Continue。
我现在的方法就是不在这个地方判断，把所有的死亡音效都Hook住了，之后在
`Broadcast_DeathSound()` 函数中判断是否存在死亡音效。

**Comment by Kxnrl** [comment]
你可以试试最新的

**Comment by Kxnrl** [comment]
用1.10的. 
store 2.5之后会要求SM 1.10 6371+

**Comment by Illyasviels** [comment]
好的 我试试

**Comment by Illyasviels** [comment]
我在最新的365行添加了 `PrintToChat(client, "Replace Death Sound to [%s]", g_szDeathVoice[client]);`
在游戏中装备模型后被bot打死，聊天框给的是`Replace Death Sound to []`。
我怀疑是`public Action Hook_NormalSound`这个函数里面获取不到全局g_szDeathVoice[client]的值。

**Comment by Kxnrl** [comment]
你可以加一个sm_test指令来检查输出是否玩家带不带有这个变量. 
现在SoundHook是怎么样都不会有声音吗

**Comment by Illyasviels** [comment]
我用sm_test可以正常输出音效所在路径，并且在SoundHook函数里面用`PrintToChat(client, "Replace Death Sound to [%s]", g_ePlayerSkins[client][szModel]);`也可以获取到模型路径。
按这样来说的话，可能死亡之前执行了哪个函数导致`g_szDeathVoice[client][0] = '\0'`比SoundHook函数优先触发了。

**Comment by Kxnrl** [comment]
这个版本你得自己编译

**Comment by Illyasviels** [comment]
我找到了解决办法
```
    if(g_ePlayerSkins[client][szSound][0] != 0)
        FormatEx(g_szDeathVoice[client], 256, "*%s", g_ePlayerSkins[client][szSound]);

    // allow sound
    if(g_szDeathVoice[client][0] != '*')
        return Plugin_Continue;
```
就是在这句话之前再初始化一次g_szDeathVoice[client]就正常了。

**Comment by Kxnrl** [comment]
g_ePlayerSkins 并不是对应client index的数组.
g_ePlayerSkins 对应的是Store Data Index

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/commit/c21dbd4e5087a82187d9b4d96d32bf701d210aaa 这个应该可以了

**Comment by Illyasviels** [comment]
嗯 修复了
