### ISSUE TITLE
Store don't add files to the precache / download table

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#37]
https://gamebanana.com/skins/167448
Skin is "Harry Potter"

server: https://puu.sh/CmHLK/82cb98f1ca.png
player: https://puu.sh/CmHLj/20b6644552.png

error console: https://pastebin.com/EJEGLkn9

**Comment by Caaine** [comment]
error from client

**Comment by Kxnrl** [comment]
install this -> https://forums.alliedmods.net/showthread.php?p=602270
set up download_simple.ini
