### ISSUE TITLE
有办法修复一下大逃杀模式的手膜吗- -

### ISSUE THREAD

**Issue by Illyasviels** [Kxnrl/Store#38]
大逃杀模式的手膜没有改变，还是原本的。。但是第三人称有模型。

**Comment by Kxnrl** [comment]
ArmsFix

**Comment by Illyasviels** [comment]
我编译后加载了 但是没有效果。。

**Comment by Kxnrl** [comment]
重启过了吗

**Comment by Illyasviels** [comment]
05 "[CSGO] Arms Fix" (1.5) by Kyle
19 "Store - The Resurrection" (2.3.463) by Kyle
两个都加载了，也重启了。

**Comment by Kxnrl** [comment]
截个图看看第一人称视角

**Comment by Illyasviels** [comment]
[preview-hand-mdl](http://www.mango-pomelo.top/file_pool/preview-hand-mdl.jpg)

**Comment by Illyasviels** [comment]
可以修复吗。。

**Comment by Kxnrl** [comment]
还没有时间去看

**Comment by Illyasviels** [comment]
我不急，你先忙

**Comment by Illyasviels** [comment]
mp_weapons_allow_heavyassaultsuit 0
我关闭了重型装甲就可以了。应该是这个问题

**Comment by Kxnrl** [comment]
mp_weapons_allow_heavyassaultsuit 一般的服务器都不会开的
如果要设置.直接用SetEntProp就可以
