### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by IZMatyi** [Kxnrl/Store#39]
Can you help me with installing, i have many errors im not updating from zephs store so how does this work. What do i import to my database?

**Comment by IZMatyi** [comment]
I cannot upload the database file it says that Specified key was too long; max key length is 767 bytes

**Comment by Kxnrl** [comment]
full error log?

**Comment by Drmohammad11** [comment]
hi!
this error:
SQL query:


CREATE TABLE `store_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `player_id` int(11) NOT NULL,
  `type` varchar(16) NOT NULL,
  `unique_id` varchar(192) NOT NULL DEFAULT '',
  `date_of_purchase` int(11) unsigned NOT NULL DEFAULT '0',
  `date_of_expiration` int(11) unsigned NOT NULL DEFAULT '0',
  `price_of_purchase` int(11) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `p` (`player_id`,`type`,`unique_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4
MySQL said: Documentation

#1071 - Specified key was too long; max key length is 767 bytes

**Comment by Kxnrl** [comment]
hey, man , are u still alive?

**Comment by Drmohammad11** [comment]
hi Kxnrl!!
I Very try Install This Store But Very Very it's difficult!
I could not install this plugin.
  Can you give a complete tutorial ??

**Comment by Kxnrl** [comment]
u upgrade from zephyrus store ?

**Comment by Kxnrl** [comment]
> > u upgrade from zephyrus store ?
> 
> no, new install

install follow guide. any question we can talk here.

**Comment by Drmohammad11** [comment]
> > > u upgrade from zephyrus store ?
> > 
> > 
> > no, new install
> 
> install follow guide. any question we can talk here.

ok. thank you

**Comment by marius892000** [comment]
Can you please help me with this error?
Exception reported: Can not retrieve item.child from database: no result row

**Comment by Kxnrl** [comment]
> Can you please help me with this error?
> Exception reported: Can not retrieve item.child from database: no result row

U need import item to your sql databse
