### ISSUE TITLE
Vip with flag?(Question)

### ISSUE THREAD

**Issue by ZeitZumKiffen** [Kxnrl/Store#41]
Hey, thanks for your version and a little question....i upgrade my version from zep to yours with problems, but after 3 days, is it working^^ But how i can set a flag on items? i use the line "vip"  "1" for your store but thats not the flag "a" how i can fix or change that?

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/blob/master/include/store_stock.inc#L414-L427

**Comment by Kxnrl** [comment]
yes. of course.

**Comment by ZeitZumKiffen** [comment]
k, thank you
