### ISSUE TITLE
Errors when importing additem.sql

### ISSUE THREAD

**Issue by Wh1t3Rose** [Kxnrl/Store#43]
Hello I created a new store database and uploaded databases.sql to my store DB. Then I imported additem.sql and got the errors:

```
Warning in ./libraries/sql.lib.php#613
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'store',
string 'store_item_child',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `store_item_child`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'store',
string 'store_item_child',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `store_item_child`',
NULL,
NULL,
)
```

Then the plugin on my server error:
`store.smx (Store - The Resurrection): Can not retrieve item.child from database: no result row`

**Comment by Kxnrl** [comment]
before additem. u need add parents

**Comment by Wh1t3Rose** [comment]
I did but that gave errors as well. One sec and I will provide error.

**Comment by Wh1t3Rose** [comment]
When I import database.sql
```
Error

SQL query:

ALTER TABLE `store_item_child`
ADD `idle` varchar(32) NOT NULL DEFAULT 'ITEM_NO_IDLE' COMMENT 'pet',
ADD `run` varchar(32) NOT NULL DEFAULT 'ITEM_NO_RUN' COMMENT 'pet',
ADD `death` varchar(32) NOT NULL DEFAULT 'ITEM_NO_DEATH' COMMENT 'pet',
ADD `seed` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `weart` tinyint(3) NOT NULL DEFAULT '-1' COMMENT 'weaponskin',
ADD `paint` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `wearf` float(7,6) unsigned NOT NULL DEFAULT '0.01' COMMENT 'weaponskin'

MySQL said: Documentation
#1060 - Duplicate column name 'idle'
```

Importing InsertParent did not produce an error

Then importing additem.sql:
```
SQL query:

INSERT INTO `store_item_child` 
(
    `parent`,
    `type`,
    `uid`,
    `buyable`,
    `giftable`,
    `only`,
    `auth`,
    `vip`,
    `name`,
    `1d`,
    `1m`,
    `pm`,
    `slot`,
    `model`,
    `worldmodel`,
    `dropmodel`,
    `weapon`
) 
VALUES 
(
    '{YOUR PARENT ID FROM store_item_parent}',      'hat',                                          '{unique_identifier}',                          '1',                                            '1',                                            '0',                                            'ITEM_NOT_PERSONAL',                            '0',                                            '{Item name in store main menu}',               '{price of 1 day}',                             '{price of 1 month}',                           '{price of permanent}',                         '{Store unique Slot}'                           '{view model path}',                            '{world model path}',                           '{drop mode[...]

MySQL said: Documentation
#1136 - Column count doesn't match value count at row 1
```


My Database:
![image](https://user-images.githubusercontent.com/4251482/51010419-3abc4880-1522-11e9-9266-b37bda8019e2.png)

**Comment by Kxnrl** [comment]
Did you see comments in database.sql?

**Comment by Kxnrl** [comment]
And that parent ID is an int data. 
ez to find in store_item_parent. the 'id' filed it is.

**Comment by Wh1t3Rose** [comment]
No I did not but the only comments I see now is about upgrading from 2.0 and 2.2 which I am not doing.

**Comment by Kxnrl** [comment]
If u install from >= 2.2 , u don't need to ALTER TABLE.

**Comment by Wh1t3Rose** [comment]
I'm sorry but I do not understand. I am doing a fresh install on a fresh database. So I am not upgrading anything. I should be able to just import your database/.sql and addparent.sql without errors but that isn't the case.

Can you provide me a sql file with fixed code please?

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/issues/13
https://github.com/Kxnrl/Store/issues/7#issuecomment-343781861

**Comment by Kxnrl** [comment]
u upgrade from zephyr store?

**Comment by Wh1t3Rose** [comment]
Can I give you a login for my Store DB and have you take a look? I also can send you an email with a link to my php files hosted on my webserver as well if you need to look at them

**Comment by Kxnrl** [comment]
okay.

**Comment by Wh1t3Rose** [comment]
@Kxnrl I emailed you

**Comment by Wh1t3Rose** [comment]
@Kxnrl Were you able to login?

**Comment by Kxnrl** [comment]
sry, i am still on a trip.

**Comment by Wh1t3Rose** [comment]
Oh no problem!

**Comment by Kxnrl** [comment]
hey, i am working on your mysql db

**Comment by Kxnrl** [comment]
u need to add "uid" key in your item config. 
example:
![image](https://user-images.githubusercontent.com/3905845/51431230-e2dbbb00-1c60-11e9-9fa0-5ac47670d81b.png)

**Comment by Kxnrl** [comment]
that uid must be unique

**Comment by Wh1t3Rose** [comment]
Ok I'll do this and will report back. Thanks!

**Comment by Kxnrl** [comment]
replace
