### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by xSL0W** [Kxnrl/Store#45]
Hello, when I want to install your shop but I've got these errors:
https://hastebin.com/gogarufive.cpp
Can someone help me?

**Comment by Kxnrl** [comment]
u should import data to your database before start server.

**Comment by z4cH3r** [comment]
hey, i'm also having this problem. didn't understand how to resolve it
any help?

**Comment by z4cH3r** [comment]
L 02/15/2019 - 15:33:19: [SM] Exception reported: Can not retrieve item.child from database: no result row
L 02/15/2019 - 15:33:19: [SM] Blaming: store/store.smx
L 02/15/2019 - 15:33:19: [SM] Call stack trace:
L 02/15/2019 - 15:33:19: [SM]   [0] SetFailState
L 02/15/2019 - 15:33:19: [SM]   [1] Line 3000, addons/sourcemod/scripting/store.sp::UTIL_ReloadConfig
L 02/15/2019 - 15:33:19: [SM]   [2] Line 2253, addons/sourcemod/scripting/store.sp::SQLCallback_Connection

**Comment by xSL0W** [comment]
I don't know,I didn't found a way to install it

**Comment by z4cH3r** [comment]
noice

**Comment by z4cH3r** [comment]
@Kxnrl any help?

**Comment by Kxnrl** [comment]
Using php script to import item data. Did you use Zephyr store before?

**Comment by z4cH3r** [comment]
@Kxnrl 
nope, clean installation, new db, new server

**Comment by xSL0W** [comment]
I am not retarded but I tried to install it step by step and didn't worked. Now I am using zephyrus store and I want to switch to a newer shop plugin and I found this one. If someone has any ideea about what I am doing wrong please answer.

**Comment by Kxnrl** [comment]
If you switch from zeph store, Using php script to import item data.
If clean install, run importItem.sql or importParent.sql to import data.

**Comment by xSL0W** [comment]
I will give it a try tomorrow, thanks for help

**Comment by Kxnrl** [comment]
read this and exec -> parents
https://github.com/Kxnrl/Store/blob/master/utils/addparent.sql

read this and exec -> item
https://github.com/Kxnrl/Store/blob/master/utils/additem.sql

**Comment by z4cH3r** [comment]
@Kxnrl 
so basicly everytime that i want to add skin or whatever i would need to use 
https://github.com/Kxnrl/Store/blob/master/utils/additem.sql ?

example i want to use you items.txt that you have, how do i make the db?

**Comment by Kxnrl** [comment]
> @Kxnrl
> so basicly everytime that i want to add skin or whatever i would need to use
> [/utils/additem.sql@`master`](https://github.com/Kxnrl/Store/blob/master/utils/additem.sql) ?
> 
> example i want to use you items.txt that you have, how do i make the db?

1. sure. or you can add 1 row in table manually.
2. https://github.com/Kxnrl/Store/issues/7#issuecomment-343781861

**Comment by z4cH3r** [comment]
@Kxnrl why don't you do it like default zephyr so it can be automatic?
also can you upload maybe the 2 lines for the `store_item_child` because in #7 it's not the full one

**Comment by Kxnrl** [comment]
this plugin made for multi-server community. so all data saved in mysql.

**Comment by z4cH3r** [comment]
yeah i get that and your shop looks awesome, but to maintain it and remove or adding stuff looks pain in the ass...
