### ISSUE TITLE
sql mode not mysql possible?

### ISSUE THREAD

**Issue by Ayrton09** [Kxnrl/Store#46]
hello sorry for open an issue for this but there is a way to install this store without mysql? would be great!.

**Comment by Kxnrl** [comment]
i mean using sqlite or other nosql db?

**Comment by Ayrton09** [comment]
ohhh ok thank you for answer.

**Comment by Ayrton09** [comment]
hello again, im installing this with mysql everything is working but when i import the database.sql i got to many errors

Error
consulta SQL:


CREATE TABLE `store_players` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `authid` varchar(32) NOT NULL,
  `name` varchar(64) NOT NULL,
  `credits` int(11) NOT NULL,
  `date_of_join` int(11) NOT NULL,
  `date_of_last_join` int(11) NOT NULL,
  `ban` int(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `authid` (`authid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4
![chrome_2ida6bt2p8](https://user-images.githubusercontent.com/47057206/52065367-2386de80-2555-11e9-858f-421c266b3976.png)
![chrome_it7tlbalne](https://user-images.githubusercontent.com/47057206/52065372-2681cf00-2555-11e9-9d8f-1e4dd7e7c67e.png)

**Comment by Ayrton09** [comment]
L 01/31/2019 - 14:05:26: [SM] Exception reported: Can not retrieve item.parent from database: Table 'store.store_item_parent' doesn't exist
L 01/31/2019 - 14:05:26: [SM] Blaming: store.smx
L 01/31/2019 - 14:05:26: [SM] Call stack trace:
L 01/31/2019 - 14:05:26: [SM]   [0] SetFailState
L 01/31/2019 - 14:05:26: [SM]   [1] Line 2996, addons/sourcemod/scripting/store.sp::UTIL_ReloadConfig
L 01/31/2019 - 14:05:26: [SM]   [2] Line 2253, addons/sourcemod/scripting/store.sp::SQLCallback_Connection

**Comment by Ayrton09** [comment]
yes i just imported database haha sorry im new on database

**Comment by Ayrton09** [comment]
hello, idk what means
"Import SQL table to your database. ( SQL scripts: addons/sourcemod/configs/database.sql )"
what i need to do?

**Comment by Kxnrl** [comment]
done it?

**Comment by Ayrton09** [comment]
hello i got this error. xception reported: Can not retrieve item.child from database: no result row
