### ISSUE TITLE
Can't Equip items

### ISSUE THREAD

**Issue by MRKurama** [Kxnrl/Store#48]
https://imgur.com/a/4ih4rj7

that's my problem, i can't equip the item, /inv doesn't work either
and i would like for it not to look like it does right now.
in the picture i sent just now, there's [TE], and i would like not to have it, 
but have in the character models category, i woud like to have a sub-category that will be called, Terrorists.
Thx, waiting for your reply

**Comment by MRKurama** [comment]
the store works once, then i restart the server and then it doesnt work anymore,
prints to chat: [Store] Please wait. Your inventory hasn't been fetched yet.

**Comment by z4cH3r** [comment]
@MRKurama 
hey, how you manage to successfully install it?
me and one other dude have this problem
https://github.com/Kxnrl/Store/issues/45

**Comment by Kxnrl** [comment]
I don't think the database server has responded to the request yet.
Try to dump all sql queries from MySQL server.

**Comment by rajkodev** [comment]
@Kxnrl Tried everything with SQL server, restarted it a few times, still same issue. Rest of plugins works perfect on that SQL server. Any other suggestions, where should i look?

**Comment by Kxnrl** [comment]
> @Kxnrl用SQL服务器尝试了一切，重启了几次，仍然是同样的问题。其余插件在该SQL服务器上运行良好。任何其他建议，我应该在哪里看？

Import items to database.

**Comment by KillStr3aK** [comment]
+1
