### ISSUE TITLE
Problem in install / Chat processor question

### ISSUE THREAD

**Issue by Toxiic57** [Kxnrl/Store#49]
Hi, sorry to bother but i got a problem in my install that i really don't understand.

So, it's a fresh install, i follow the guide and i get this error : 
 
`store.smx (Store - The Resurrection): Can not retrieve item.child from database: no result row`

So if i understand it's a problem with the item item childs and parents things on DB entry ? 
If i check the  store_item_parent table i got :

![storeitemparent1](https://user-images.githubusercontent.com/23276901/54307132-31effd80-45cb-11e9-9063-a466887417ce.PNG)
![storeitemparent2](https://user-images.githubusercontent.com/23276901/54307137-36b4b180-45cb-11e9-82e0-f7068ef82fcb.PNG)

And in the store_item_child table : 
![storeitemchild](https://user-images.githubusercontent.com/23276901/54307275-898e6900-45cb-11e9-9a7b-6817776058de.PNG)

and all the item wich is in items.txt that is in the config

But in store_items and store_equipment there is nothing, did i need to add the items here ? And how can i put them here ? Or did i miss something somewhere ? :(

And second thing, why  the store disabling this chat-processor ? https://forums.alliedmods.net/showthread.php?p=2448733
Because without this chat processor i can't use this plugin : https://forums.alliedmods.net/showthread.php?p=2566623 wich is pretty nice for all this tags things. Any compatibility possible ? 

Thank's ! <3

**Comment by rajkodev** [comment]
I have same problem, and it looks like deadend for me, until developer explain us where is a problem!
<3

**Comment by Kxnrl** [comment]
1. make sure your database.cfg in addons/sourcemod/configs
2. when I started this project. CP hasn't been created yet.
3. I made a CP bridge/invoke https://github.com/Kxnrl/Store/commit/984b7d539ddb19e82d2d1c2b79c42abc48c18efb

**Comment by Toxiic57** [comment]
My db config is ok, 
For CP did i just need to compile cpsupport.sp and throw it in the plugins folder ?
