### ISSUE TITLE
Doesnt see Wings/Masks

### ISSUE THREAD

**Issue by rajkodev** [Kxnrl/Store#50]
I compilled a new version, and with old one on ZE server when i use !tp i see my Hats, Mask, Wings, but when i compilled new version for surf server i dont see anything of that, except player model.

Everyone else see my mask, wings etc.. Except myself.
![20190327120133_1](https://user-images.githubusercontent.com/24896853/55071170-2222ef80-5088-11e9-98d5-b9a22fb0e6a4.jpg)

**Comment by Kxnrl** [comment]
Can anyone else see it?

**Comment by rajkodev** [comment]
Everyone else see, except me.
And every player cannot see their own, but can se others.
