### ISSUE TITLE
Which plugin for CSGO Surf?

### ISSUE THREAD

**Issue by Wh1t3Rose** [Kxnrl/Store#54]
Which plugin do I use for surf?

Also how do I fix this error?

```
Error: Table 'store-dev.store_equipment' doesn't exist
```

I think i have to create the table but how do I know what columns to make and stuff?

**Comment by Kxnrl** [comment]
check database.sql

**Comment by Wh1t3Rose** [comment]
You've made this painful for regular people. Can't you just provide a database dump that has most hats, pets, etc in it already?

**Comment by Wh1t3Rose** [comment]
@Kxnrl

**Comment by Kxnrl** [comment]
exists db is out-of-date

**Comment by Kxnrl** [comment]
u can import by yourself manually
