### ISSUE TITLE
Server Crash When Join

### ISSUE THREAD

**Issue by whtevrwt** [Kxnrl/Store#56]
Hi.

My server keeps crashing when I join. I added the items to the database using the php script and I validate everything. But when I join my server, it crashes. I don't know what I'm doing wrong.

**Comment by Kxnrl** [comment]
share crash id here..

**Comment by whtevrwt** [comment]
Is that the -debug ?

**Comment by Kxnrl** [comment]
https://forums.alliedmods.net/showthread.php?t=277703

**Comment by whtevrwt** [comment]
I dont get any logs. I notice it only crashes when I pick a team. If I join spectator, everything is ok.

**Comment by Kxnrl** [comment]
Did u equip any item?

**Comment by whtevrwt** [comment]
No. Its a fresh install. I just install the plugin.

**Comment by Kxnrl** [comment]
Any data in your sql table store_item_equipment?

**Comment by geferon** [comment]
I have discovered that this crash is due to the Aura module, crashing whenever the PrecacheGeneric gets called, probably due to late game precache not being available in CSGO or some sort of error due to file availability? I'm going to investigate more and report here.

**Comment by geferon** [comment]
I don't know if this might be related to my issue or not but, this seems like the server is crashing when trying to precache an invalid resource, as you may not have setup properly the "model" property inside of the database.

**Comment by whtevrwt** [comment]
> 
> 
> Any data in your sql table store_item_equipment?

I don't have a store_item_equipment sql table. These are my tables: https://imgur.com/8YJccfK

**Comment by Kxnrl** [comment]
> > Any data in your sql table store_item_equipment?
> 
> I don't have a store_item_equipment sql table. These are my tables: [imgur.com/8YJccfK](https://imgur.com/8YJccfK)
> 
> And this is my items.txt: [pastebin.com/4w0yvMgK](https://pastebin.com/4w0yvMgK)

create tables before start server.
