### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Toxiic57** [Kxnrl/Store#57]
Hi ! 
So i'm trying to install this store on a fresh install, but i got problem with the DB : 

store.smx (Store - The Resurrection): Can not retrieve item.child from database: no result row

So if i understand i need to import item, but i didn't understand how ? With one of those php script ?

**Comment by Kxnrl** [comment]
emm, Did you switch from zephyrus store?

**Comment by Toxiic57** [comment]
Nop, fresh install, no upgrade

**Comment by Toxiic57** [comment]
I got this in the error log 

===========================[2019-06-16 14:57:38]===========================
Message: Failed to fetch playerId from array.SELECT `id`,`credits` FROM `store_players` WHERE `authid` = '1:44083262' LIMIT 1;
Stack Trace: 
#0 /var/www/html/store/example.php(32): Store\Player->__construct('765611980484322...')
#1 /var/www/html/store/example.php(56): testPlayer()
#2 {main}

**Comment by Kxnrl** [comment]
emm, that is example php script for php developer.
If fresh installed, you need import items into database.
Using addItem/addParent sql script.
Do not run sql script directly.

**Comment by Toxiic57** [comment]
Have you an example of how to use addItem/addParent script please ? 
Or maybe can you provide a filled DB ?

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/blob/master/utils/additem.sql
and 
https://github.com/Kxnrl/Store/blob/master/utils/addparent.sql

just replace value in the quota

**Comment by Toxiic57** [comment]
Do i have to put all item one per one item which are in the items.txt ?
Can i save time if i upgrade a DB used for Zeph Store ?

**Comment by Kxnrl** [comment]
Yes. But if exists items.txt, you can try php script.
If upgrade from zepyhrus store, Just import items.txt via php script.

**Comment by Toxiic57** [comment]
Which php script can i use for import items.txt ?

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/blob/master/utils/insertItem.php
https://github.com/Kxnrl/Store/blob/master/utils/insertParent.php

### Install guide
https://github.com/Kxnrl/Store#how-to-install

**Comment by Toxiic57** [comment]
So, there is the result when i use the php script with the items.txt which you provide on this repo  : 

https://gamepanel.ethernitygaming.fr/store/insertParent.php
https://gamepanel.ethernitygaming.fr/store/insertItem.php

It says duplicate entry because we already get the entry in the items.child/parent table but not it items :
 
![1](https://user-images.githubusercontent.com/23276901/59565808-17a93e00-9058-11e9-9c8e-c08ee331a857.png)

![2](https://user-images.githubusercontent.com/23276901/59565850-7a023e80-9058-11e9-89fc-2fca530a4cbc.png)

![3](https://user-images.githubusercontent.com/23276901/59565860-8d150e80-9058-11e9-976d-7d212d3f3979.png)

**Comment by Toxiic57** [comment]
There is a thing i don't understand, on the screenshot from my DB above you can see i get something in store_items_child, but the error is " Can not retrieve item.child from database: no result row "

**Comment by Kxnrl** [comment]
emmm. the items.txt is an example. if you want to find a exists db.
try this https://github.com/Kxnrl/Store/issues/7#issuecomment-343781861

**Comment by Kxnrl** [comment]
maybe that is out-of-date.

**Comment by Toxiic57** [comment]
It's okay for the db it has been filled with the item_child and item_prents and if I good understood the items table should be empty. But the problem is that the plugin gives me the error I wrote above in comment https://github.com/Kxnrl/Store/issues/57#issuecomment-502461580 and I don't understand why and what causes this issue.

**Comment by Kxnrl** [comment]
your mysql server version?

**Comment by Kxnrl** [comment]
> 

> So, there is the result when i use the php script with the items.txt which you provide on this repo :
> 
> [gamepanel.ethernitygaming.fr/store/insertParent.php](https://gamepanel.ethernitygaming.fr/store/insertParent.php)
> [gamepanel.ethernitygaming.fr/store/insertItem.php](https://gamepanel.ethernitygaming.fr/store/insertItem.php)
> 
> It says duplicate entry because we already get the entry in the items.child/parent table but not it items :
> 
> ![1](https://user-images.githubusercontent.com/23276901/59565808-17a93e00-9058-11e9-9c8e-c08ee331a857.png)
> 
> ![2](https://user-images.githubusercontent.com/23276901/59565850-7a023e80-9058-11e9-89fc-2fca530a4cbc.png)
> 
> ![3](https://user-images.githubusercontent.com/23276901/59565860-8d150e80-9058-11e9-976d-7d212d3f3979.png)

P1 I seem you have invalid parent id in store_item_child. 
Please import parent before import child.

**Comment by Toxiic57** [comment]
So, i reimport parent before child ans i now i got something like valid value : https://prnt.sc/o2upeh

And i'm on 10.1.38-MariaDB-0+deb9u1

**Comment by Kxnrl** [comment]
now it work?

**Comment by Toxiic57** [comment]
Nop, always the same error

**Comment by Kxnrl** [comment]
look like same bug i seem before, on sm 1.9?

**Comment by Toxiic57** [comment]
Yep SM 1.9.0.6280

**Comment by Kxnrl** [comment]
sm 1.10 rebuild mysql driver , can u try for the test?

**Comment by Toxiic57** [comment]
Yep, i gonna try

**Comment by Toxiic57** [comment]
Same with latest 1.10

**Comment by Toxiic57** [comment]
So, with SM 1.10 ans plugin version 1.10 do exactly the same

**Comment by Drmohammad11** [comment]
hi!
this store need to web installer like sourcebans for management!!
i very try but this plugin need web installer.
models and other files not find !!  :/

**Comment by Toxiic57** [comment]
If you need to test something just tell me, i don't know what to anymore actually with this problem

**Comment by Toxiic57** [comment]
Any news ?

**Comment by Kxnrl** [comment]
WIP

**Comment by Toxiic57** [comment]
Hi ! 
I found this in my log, never see that before, don't know if it related but there it is : https://pastebin.com/nBps5Wf1

**Comment by Kxnrl** [comment]
are u sure data exists?

**Comment by Toxiic57** [comment]
Yes there is data in the DB

**Comment by Kxnrl** [comment]
Did u try run query in console?
```sql
SELECT a.*,b.name as title FROM store_item_child a LEFT JOIN store_item_parent b ON b.id = a.parent ORDER BY b.id ASC, a.team ASC, a.parent ASC, a.pm ASC
```

**Comment by Toxiic57** [comment]
Yes, there is the result, seems like ok

![65764470_199487864322621_8244263439195701248_n](https://user-images.githubusercontent.com/23276901/60387646-85b52280-9aa6-11e9-8751-dd53d44b9e88.png)

**Comment by iulicxd5** [comment]
This shop plugin is working fine,just add in databases.cfg
"csgo" 
    {
        "driver"            "mysql" 
        "host"              "127.0.0.1" 
        "database"          "storecsgo"
        "user"              "root" 
        "pass"              "" //password
        //"timeout"         "0"
        //"port"            "0"
    }

**Comment by Toxiic57** [comment]
Yeah no problem for that ( just dont tell me that i should use " storecsgo " instead of " csgostore "
![b243b328c480cd4da06cd81324c50ab4](https://user-images.githubusercontent.com/23276901/60399680-9fb73980-9b68-11e9-9c45-7391bfa358f6.png)

**Comment by Kxnrl** [comment]
interesting :bug:
Look like SM db driver stuck the query.
Add my steam , i will sent u a debug version.

**Comment by Toxiic57** [comment]
Done :)

**Comment by Kxnrl** [comment]
what's your steam nick

**Comment by Toxiic57** [comment]
[ETH] Yvano / https://steamcommunity.com/id/Yvano/

**Comment by Toxiic57** [comment]
Fix working fine for me ! Thanks ! :) 🥓 🥓
