### ISSUE TITLE
can't compile the Store

### ISSUE THREAD

**Issue by Caaine** [Kxnrl/Store#58]
//// store.sp
//
// C:\Users\Caaine\Desktop\scripts\include\store_stock.inc(7) : error 050: constant 'szName' already defined
// C:\Users\Caaine\Desktop\scripts\include\store_stock.inc(28) : error 050: constant 'iId' already defined
// C:\Users\Caaine\Desktop\scripts\include\store_stock.inc(39) : error 050: constant 'iId' already defined
// C:\Users\Caaine\Desktop\scripts\include\store_stock.inc(58) : error 050: constant 'szPlFile' already defined
// store/modules/skin.sp(9) : error 050: constant 'szModel' already defined
// store/modules/trail.sp(7) : error 050: constant 'iSlot' already defined
// store/modules/trail.sp(19) : error 032: array index out of bounds (variable "g_eTrails")
// store/modules/trail.sp(50) : error 032: array index out of bounds (variable "g_eTrails")
// store/modules/trail.sp(57) : error 032: array index out of bounds (variable "g_eTrails")
// store/modules/trail.sp(118) : error 032: array index out of bounds (variable "g_eTrails")
// store/grenades.sp(5) : error 050: constant 'szModel' already defined
// store/grenades.sp(13) : error 050: constant 'szMaterial' already defined
// store/grenades.sp(70) : error 032: array index out of bounds (variable "g_eGrenadeSkins")
// store/grenades.sp(88) : error 032: array index out of bounds (variable "g_eGrenadeTrails")
// store/grenades.sp(101) : error 032: array index out of bounds (variable "g_eGrenadeSkins")
// store/grenades.sp(111) : error 032: array index out of bounds (variable "g_eGrenadeSkins")
// store/models.sp(16) : error 050: constant 'iSlot' already defined
// store/sounds.sp(11) : error 050: constant 'szName' already defined
// store/sounds.sp(48) : error 032: array index out of bounds (variable "g_eSounds")
// store/sounds.sp(51) : error 032: array index out of bounds (variable "g_eSounds")
// store/sounds.sp(72) : error 032: array index out of bounds (variable "g_eSounds")
// store/sounds.sp(87) : error 032: array index out of bounds (variable "g_eSounds")
// store/sounds.sp(189) : error 032: array index out of bounds (variable "g_eSounds")
// C:\Users\Caaine\Desktop\scripts\store.sp(589) : error 032: array index out of bounds (variable "g_eClientItems")
// C:\Users\Caaine\Desktop\scripts\store.sp(710) : error 032: array index out of bounds (variable "g_eClientItems")
// C:\Users\Caaine\Desktop\scripts\store.sp(714) : error 032: array index out of bounds (variable "g_eClientItems")

**Comment by Kxnrl** [comment]
after Alliedmodders changed sp syntax, can not compile. just downgrade compiler version to SM1.10.6371.

**Comment by Caaine** [comment]
atfer downgrade to SM 10.6371 from her https://www.sourcemod.net/smdrop/1.10/sourcemod-1.10.0-git6371-windows.zip

dosn't work for me

**Comment by Kxnrl** [comment]
build script using sm 1.10.6366, try this

**Comment by Caaine** [comment]
this works
