### ISSUE TITLE
SetParentAttachmentMaintainOffset

### ISSUE THREAD

**Issue by iulicxd5** [Kxnrl/Store#59]
Please help me with pets,i tried to add pets,when i equip a pet,in console an error is appearing:
ERROR: Tried to SetParentAttachmentMaintainOffset for entity prop_dynamic (prop_dynamic), but it has no attachment named letthehungergamesbegin.
And model is not prechaching (not downloading)

**Comment by Kxnrl** [comment]
attachment does not exists.

**Comment by iulicxd5** [comment]
and how to fix?

**Comment by Kxnrl** [comment]
change attachment name, e.g. c4

**Comment by iulicxd5** [comment]
where i can find,which attachment name is correct? or it will work with facemask ?

**Comment by Kxnrl** [comment]
open model with CSGOSDK-Model viewer

**Comment by iulicxd5** [comment]
okey thank you,i will try!

**Comment by iulicxd5** [comment]
i changed attachment name in database,it also do not work
maybe because store_pet.sp have
SetVariantString("letthehungergamesbegin");
AcceptEntityInput(entity, "SetParentAttachmentMaintainOffset", entity, entity, 0);
?

**Comment by iulicxd5** [comment]
Please,Maybe you will compile this script with removing this 2 statements:
`SetVariantString("letthehungergamesbegin");
AcceptEntityInput(entity, "SetParentAttachmentMaintainOffset", entity, entity, 0);`
or putting instead of letthehungergamesbegin - facemask or c4 or something else.
Because i have errors when i compile store_pet.sp

**Comment by Kxnrl** [comment]
if pet still working, just ignore this error report.
Did you test if delete that 2 lines?

**Comment by iulicxd5** [comment]
This errors appears many times in console,especially if many players have buyed pets and equipped them,
They are appearing when player is spawned
I can not test because of having errors when compilling store_pet.sp
![Безымянный](https://user-images.githubusercontent.com/52352600/60494602-c89a1480-9cb7-11e9-8ac2-cb31036733da.png)

**Comment by Kxnrl** [comment]
downgrade compiler version to 6370 or lower

**Comment by iulicxd5** [comment]
It will compile only removing this variables.
I deleted:
```
SetVariantString("letthehungergamesbegin");
AcceptEntityInput(entity, "SetParentAttachmentMaintainOffset", entity, entity, 0);
```
And now is working without errors.
