### ISSUE TITLE
MYSQL error 

### ISSUE THREAD

**Issue by 66venum** [Kxnrl/Store#60]
Hi ! 
I have a problem with the SQL connexion...  But my database.cfg have the corrects infos... 

store.error.log : 
Failed to connect to SQL database. [001] Error: Could not find driver "mysql"

How can I fix this problem ?

PS: when I import the database.sql on my PhpMyAdmin, I have somes VARCHAR errors... But I fixed this

Thanks for help !
![affd05094de061787843eda924ba45d4](https://user-images.githubusercontent.com/46488156/60686382-b16e4900-9ea8-11e9-8d60-6ceedd1c19af.png)

![de5c0be40a45d11589e589795db252c1](https://user-images.githubusercontent.com/46488156/60686408-cea31780-9ea8-11e9-8902-04744660ae60.png)

![e1fd7da2c5742f8702b7ac5c326caba9](https://user-images.githubusercontent.com/46488156/60686466-22adfc00-9ea9-11e9-89e0-3cc22a8e768c.png)

**Comment by Kxnrl** [comment]
reinstall you sm

**Comment by 66venum** [comment]
Error fixed
