### ISSUE TITLE
Add Custom Weapons Store

### ISSUE THREAD

**Issue by paulocrash** [Kxnrl/Store#63]
In future upgrades could include the Custom Weapons in the Store as an option.

The version of Store by Zephyrus already had in the case, it would be [Custom Weapon 3.0] (https://forums.alliedmods.net/showpost.php?p=2377630&postcount=80)

Latest Version: https://forums.alliedmods.net/attachment.php?attachmentid=151153&d=1452715626

Would it be possible in future updates?

**Comment by Kxnrl** [comment]
Are u blind?

**Comment by paulocrash** [comment]
> Você está cego?

Wow, pardon, it really does, I only went 3 times and did not see, sorry. :)

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/Store/blob/master/store/models.sp
