### ISSUE TITLE
What plugin do I use for CS:GO 5v5 Competitive? 

### ISSUE THREAD

**Issue by MrAmos123** [Kxnrl/Store#65]
This isn't clear in any of the documents and these two-letter abbreviations really don't make it easier...

What do I use for CS:GO 5v5 Comp gamemode?

**Comment by paulocrash** [comment]
You already have the version for Competitive, use the version of the plugin: `//GM_PR -> pure|competitive server
`

**Comment by Kxnrl** [comment]
store_pr.smx
