### ISSUE TITLE
Exception reported: Invalid event PTaH_HookType specified on the new PTAH version V1.1.0-build15

### ISSUE THREAD

**Issue by freakexeuLow** [Kxnrl/Store#68]
`L 07/28/2019 - 08:50:26: SourceMod error session started
L 07/28/2019 - 08:50:26: Info (map "surf_greatriver_xdre4m_csgo") (file "/home/user2-4/server/csgo/csgo/addons/sourcemod/logs/errors_20190728.log")
L 07/28/2019 - 08:50:26: [SM] Exception reported: Invalid event PTaH_HookType specified
L 07/28/2019 - 08:50:26: [SM] Blaming: store_weaponskin.smx
L 07/28/2019 - 08:50:26: [SM] Call stack trace:
L 07/28/2019 - 08:50:26: [SM]   [0] PTaH
L 07/28/2019 - 08:50:26: [SM]   [1] Line 59, addons/sourcemod/scripting/store_weaponskin.sp::OnPluginStart
L 07/28/2019 - 08:50:26: [SM] Unable to load plugin "store_weaponskin.smx": Error detected in plugin startup (see error logs)`

**Comment by Kxnrl** [comment]
we need to update weaponskin module following PTaH upgraded

**Comment by Bara** [comment]
I made a pull request for this with support for older version.

#69

**Comment by Kxnrl** [comment]
> I made a pull request for this with support for older version.
> 
> #69

Did you test on community server?

**Comment by Bara** [comment]
No, I the made the change through github editor.

**Comment by freakexeuLow** [comment]
@Bara 
thanks but i just remove the line and add your fix and try to compile it, but he say me this here
// C:\Users\freak\OneDrive\Desktop\sm 1.10\addons\sourcemod\scripting\store_weaponskin.sp(59) : error 100: function prototypes do not match
// C:\Users\freak\OneDrive\Desktop\sm 1.10\addons\sourcemod\scripting\store_weaponskin.sp(66) : error 100: function prototypes do not match
// C:\Users\freak\OneDrive\Desktop\sm 1.10\addons\sourcemod\scripting\store_weaponskin.sp(70) : error 017: undefined symbol "PTaH_GiveNamedItem"
