### ISSUE TITLE
Add CSGO Music Kit Store

### ISSUE THREAD

**Issue by paulocrash** [Kxnrl/Store#73]
It would be interesting if you put the option in the Store to choose CSGO Music Kit.

You currently have this plugin: https://github.com/rogeraabbccdd/Music-Kits

The idea would be to put it in the store, would that be possible?

**Comment by Kxnrl** [comment]
that will trigger gslt ban?

**Comment by paulocrash** [comment]
By logic yes, it generates the GSLT ban.

It could add and leave as an option if the server owner wants to enable this feature in case.

**Comment by Kxnrl** [comment]
Music Id store in field 'sound' (varchar)
