### ISSUE TITLE
Error import database

### ISSUE THREAD

**Issue by szogi1910** [Kxnrl/Store#81]
`ALTER TABLE `store_item_child`
ADD `idle` varchar(32) NOT NULL DEFAULT 'ITEM_NO_IDLE' COMMENT 'pet',
ADD `run` varchar(32) NOT NULL DEFAULT 'ITEM_NO_RUN' COMMENT 'pet',
ADD `death` varchar(32) NOT NULL DEFAULT 'ITEM_NO_DEATH' COMMENT 'pet',
ADD `seed` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `weart` tinyint(3) NOT NULL DEFAULT '-1' COMMENT 'weaponskin',
ADD `paint` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `wearf` float(7,6) unsigned NOT NULL DEFAULT '0.01' COMMENT 'weaponskin'

#1060 - Duplicate column name 'idle'`

@Kxnrl

**Comment by Kxnrl** [comment]
did u read comments before execute?

**Comment by szogi1910** [comment]
I read so and I do not know where I am making a mistake

**Comment by Kxnrl** [comment]
if u are fresh installion, ignore all any ALERT TABLE query
