### ISSUE TITLE
Coins display not visible

### ISSUE THREAD

**Issue by freakexeuLow** [Kxnrl/Store#84]
I have updated your system, now there are no more coins displayed in the chat, with the old version it was still possible.

**Comment by Kxnrl** [comment]
u mean !credits ?

**Comment by freakexeuLow** [comment]
yes

**Comment by Kxnrl** [comment]
any message in chat?

**Comment by freakexeuLow** [comment]
not really, its gone after the update

**Comment by Kxnrl** [comment]
commit id 509?

**Comment by freakexeuLow** [comment]
yes, this here: https://build.kxnrl.com/Store/

**Comment by Kxnrl** [comment]
can you show me the errlogs?

**Comment by freakexeuLow** [comment]
there is none, the only error is ServerInfo...https://pastebin.com/zxgzPckP

**Comment by freakexeuLow** [comment]
The store from 01/02.2019 still displayed the Credits message. The one from 09.21.2019 doesn't do it anymore, I don't have any error logs and I'm just testing myself to find out what the error is.

**Comment by Kxnrl** [comment]
> there is none, the only error is ServerInfo...https://pastebin.com/zxgzPckP
> 
> If I even reload the plugin, it restarts the map again^^

because store will force reload map to prevent server crash with late precache.

**Comment by Kxnrl** [comment]
> The store from 01/02.2019 still displayed the Credits message. The one from 09/21/2019 doesn't do it anymore, I don't have any error logs and I'm just testing myself to find out what the error is.

can you try any 500+ version?

**Comment by freakexeuLow** [comment]
> 
> 
> > The store from 01/02.2019 still displayed the Credits message. The one from 09/21/2019 doesn't do it anymore, I don't have any error logs and I'm just testing myself to find out what the error is.
> 
> can you try any 500+ version?

I will now test all 500 versions and write them which version it works with.

**Comment by Kxnrl** [comment]
except 509?

**Comment by freakexeuLow** [comment]
Did you change anything in the database?
509 (All)-499 no coins are displayed, now I test the other versions below

**Comment by Kxnrl** [comment]
I fix non-threading sql in 508

**Comment by freakexeuLow** [comment]
> 
> 
> I fix non-threading sql in 508

Okay, the problem is 508 and above. I see the Credtis in the chat with the version 505...

and another question, do you need the Items.txt in the server folder at all? He apparently pulls everything from the database anyway. I have other skins on the Surf Timer, now you can also see them on the Surf Combat Server. Items.txt are different, but databases are the same.

**Comment by Kxnrl** [comment]
> > I fix non-threading sql in 508
> 
> Okay, the problem is 508 and above. I see the Credtis in the chat with the version 505...
> 
> and another question, do you need the Items.txt in the server folder at all? He apparently pulls everything from the database anyway. I have other skins on the Surf Timer, now you can also see them on the Surf Combat Server. Items.txt are different, but databases are the same.

items.txt no longer need it.

**Comment by freakexeuLow** [comment]
> 
> 
> > > I fix non-threading sql in 508
> > 
> > 
> > Okay, the problem is 508 and above. I see the Credtis in the chat with the version 505...
> > and another question, do you need the Items.txt in the server folder at all? He apparently pulls everything from the database anyway. I have other skins on the Surf Timer, now you can also see them on the Surf Combat Server. Items.txt are different, but databases are the same.
> 
> items.txt no longer need it.

Thanks for the info and you can close the ticket if you want. I would write to you privately if it's okay and thank you for your help
