### ISSUE TITLE
Tried to look up command say as if it were a variable.

### ISSUE THREAD

**Issue by oylsister** [Kxnrl/Store#92]
I setup the plugins, there is no error on log. but when I tried to use !store it didn't show anything on screen. And when I check console, it showed this
```
Tried to look up command say as if it were a variable.
  Dirty Deeds Done Dirt Cheap :  !store
```

**Comment by Kxnrl** [comment]
plugin not working, check error logs

**Comment by h897331069** [comment]
I have the same problem. Here is the only log report

**Comment by Kxnrl** [comment]
no error logs? can u show me your plugins / exts list?

**Comment by h897331069** [comment]
L 11/15/2019 - 02:30:30: SourceMod log file session started (file "D:\csgobhop\csgo\addons\sourcemod\logs\L20191115.log") (Version "1.10.0.6454")
L 11/15/2019 - 02:30:30: [store.smx] Optional library 'clientprefs' is already loaded.
唯一生成日志

![exts list](https://user-images.githubusercontent.com/28527314/68886001-315ac880-0751-11ea-89f8-371dc498bd57.png)
拓展列表

![pulg list](https://user-images.githubusercontent.com/28527314/68886014-3a4b9a00-0751-11ea-9d8c-14506960e363.png)
插件列表

这是我的测试服务器，我按照要求安装后
输入!store没有任何反应
控制台会提示
Tried to look up command say as if it were a variable.
然后就没有任何错误日志和提示
无法正常工作

**Comment by h897331069** [comment]
L 11/15/2019 - 02:42:01: SourceMod error session started
L 11/15/2019 - 02:42:01: Info (map "kz_4u_nature") (file "D:\csgobhop\csgo\addons\sourcemod\logs\errors_20191115.log")
L 11/15/2019 - 02:42:01: [SM] Exception reported: Client index 0 is invalid
L 11/15/2019 - 02:42:01: [SM] Blaming: store.smx
L 11/15/2019 - 02:42:01: [SM] Call stack trace:
L 11/15/2019 - 02:42:01: [SM]   [0] IsClientInGame
L 11/15/2019 - 02:42:01: [SM]   [1] Line 1028, addons/sourcemod/scripting/store.sp::Command_Store
在控制台中输入命令后发现的错误.

**Comment by Kxnrl** [comment]
客户端命令为什么要在服务端控制台输入呢

**Comment by h897331069** [comment]
客户端输入没有任何提示任何反应,只会在控制台反馈
Tried to look up command say as if it were a variable.

**Comment by h897331069** [comment]
![06 FOP9TRS~~0R5 O64}F](https://user-images.githubusercontent.com/28527314/68930765-0d879900-07ca-11ea-9114-e3d8ff856e4b.png)
比如是这样,然后在服务器日志里未检测到错误日志

**Comment by Kxnrl** [comment]
物品数据导入了吗

**Comment by h897331069** [comment]
错误
SQL 查询:

-- if u upgrade from 2.0, exec this in your database
ALTER TABLE `store_item_child` ADD `idle` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_IDLE' COMMENT 'pet',
ADD `run` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_RUN' COMMENT 'pet',
ADD `death` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_DEATH' COMMENT 'pet',
ADD `seed` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `weart` TINYINT( 3 ) NOT NULL DEFAULT '-1' COMMENT 'weaponskin',
ADD `paint` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `wearf` FLOAT( 7, 6 ) UNSIGNED NOT NULL DEFAULT '0.01' COMMENT 'weaponskin';

导入时候的反馈.其他列表创建正常
![06 FOP9TRS~~0R5 O64错误
SQL 查询:

-- if u upgrade from 2.0, exec this in your database
ALTER TABLE `store_item_child` ADD `idle` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_IDLE' COMMENT 'pet',
ADD `run` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_RUN' COMMENT 'pet',
ADD `death` VARCHAR( 32 ) NOT NULL DEFAULT 'ITEM_NO_DEATH' COMMENT 'pet',
ADD `seed` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `weart` TINYINT( 3 ) NOT NULL DEFAULT '-1' COMMENT 'weaponskin',
ADD `paint` SMALLINT( 5 ) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'weaponskin',
ADD `wearf` FLOAT( 7, 6 ) UNSIGNED NOT NULL DEFAULT '0.01' COMMENT 'weaponskin';

导入时候的反馈.其他列表创建正常
}F](https://user-images.githubusercontent.com/28527314/68932104-dff01f00-07cc-11ea-98fe-82c11523e70b.png)

**Comment by Kxnrl** [comment]
大哥麻烦看看注释

-- if u upgrade from 2.0, exec this in your database

**Comment by h897331069** [comment]
![LRFKJ AI)ISS3ZM_YVMG2_Y](https://user-images.githubusercontent.com/28527314/68935478-aa026900-07d3-11ea-82d7-e6071977a1f9.png)
最后还是这样...不清楚在什么阶段发生错误..

**Comment by h897331069** [comment]
没有任何错误日志,插件在plugins list 内显示运行，但是输入命令后没有任何反馈

**Comment by Kxnrl** [comment]
可以给个截图看看store_item_parent 和 store_item_child吗

**Comment by h897331069** [comment]
![QQ图片20191116190643](https://user-images.githubusercontent.com/28527314/68992279-4eec7700-08a4-11ea-941c-1d4f51d8a52d.png)
![QQ图片20191116190548](https://user-images.githubusercontent.com/28527314/68992281-5449c180-08a4-11ea-8bd5-0ba4ad29b1e4.png)

**Comment by Kxnrl** [comment]
![image](https://user-images.githubusercontent.com/3905845/68994775-ab11c400-08c1-11ea-92e9-91398ba40581.png)
parent 应该是-1

**Comment by h897331069** [comment]
我尝试更改，但是我不是很会操作数据库....

**Comment by oylsister** [comment]
not sure that if this is caused by a table itself.
![wtf](https://user-images.githubusercontent.com/57207701/69209042-60759d80-0b88-11ea-8b68-499264e4d9df.png)

**Comment by Kxnrl** [comment]
> not sure that if this is caused by a table itself.
> ![wtf](https://user-images.githubusercontent.com/57207701/69209042-60759d80-0b88-11ea-8b68-499264e4d9df.png)

these fields are bit type

**Comment by PandaDynasty** [comment]
I'm having the same problem, as above. No logs that suggest an error.
here is my database info
![DBT03vbDaD](https://user-images.githubusercontent.com/60460774/73427086-a1fa9580-42fb-11ea-9114-2f43bca72536.png)
![nCuYG1PldJ](https://user-images.githubusercontent.com/60460774/73427088-a1fa9580-42fb-11ea-9203-34d734e855e5.png)

**Comment by Kxnrl** [comment]
> I'm having the same problem, as above. No logs that suggest an error.
> here is my database info
> ![DBT03vbDaD](https://user-images.githubusercontent.com/60460774/73427086-a1fa9580-42fb-11ea-9114-2f43bca72536.png)
> ![nCuYG1PldJ](https://user-images.githubusercontent.com/60460774/73427088-a1fa9580-42fb-11ea-9203-34d734e855e5.png)

Did you install the model files?
