### ISSUE TITLE
SQL Connection Mode

### ISSUE THREAD

**Issue by crashzk** [Kxnrl/Store#95]
I would like to know if you want to add SQL connection mode in the future? On the server itself in the case.

I know the project is focused on multi-servers, is that there are some of my servers that use Store only on it, and for me it's kind of unnecessary a MySQL database just for this server.

Thanks in advance!

**Comment by crashzk** [comment]
Any news about this feature?

I believe it could help me with my issues #127, I would test connection by SQL to see if the plugin works.

**Comment by Kxnrl** [comment]
If we use sqlite, I don't know how to import data.
I think made an plugin that read kv and import to sqlite is so stupid.
