### ISSUE TITLE
Particles are not opening in Alien Swarm SDK

### ISSUE THREAD

**Issue by iulicxd5** [Kxnrl/Store#96]
Particles which are included in this plugin are not opening in Alien Swarm SDK
`auraandtrailex.pcf
auraandtrailsbyiex.pcf
FX.pcf
iEx.pcf
iEx2.pcf
iexdmnd.pcf
iexdmnd2.pcf
iex_diamond.pcf
Trails.pcf`

**Comment by Kxnrl** [comment]
emm, these particle made by iEx.

**Comment by iulicxd5** [comment]
What does this mean?
