### ISSUE TITLE
SQL_LoadParents error

### ISSUE THREAD

**Issue by trumperypear** [Kxnrl/Store#97]
Getting this error in console:

L 12/09/2019 - 01:49:39: [SM] Exception reported: Can not retrieve item.parent from database: no result row

L 12/09/2019 - 01:49:39: [SM] Blaming: store.smx

L 12/09/2019 - 01:49:39: [SM] Call stack trace:

L 12/09/2019 - 01:49:39: [SM]   [0] SetFailState

L 12/09/2019 - 01:49:39: [SM]   [1] Line 3255, addons/sourcemod/scripting/store.sp::SQL_LoadParents

Could you please help my fix this?

**Comment by Kxnrl** [comment]
Did you import items?
