### ISSUE TITLE
Setting color to trail is not working

### ISSUE THREAD

**Issue by iulicxd5** [Kxnrl/Store#98]
When i set color for trail, in game color of trail is default
For nadetrail changing color is working

**Comment by Kxnrl** [comment]
trail color is not support.

**Comment by iulicxd5** [comment]
Please add trail color in future

**Comment by Kxnrl** [comment]
that is not TE trails

**Comment by iulicxd5** [comment]
Please, can you explain what is "TE trails"?

**Comment by Kxnrl** [comment]
https://developer.valvesoftware.com/wiki/Temporary_Entity
